// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseTimeToEnd.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageResponseTimeToEnd.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageResponseTimeToEnd_2eproto() {
  delete MessageResponseTimeToEnd::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageResponseTimeToEnd_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageResponseTimeToEnd_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::protobuf_AddDesc_MessageResponseRoundPlayerBang_2eproto();
  MessageResponseTimeToEnd::default_instance_ = new MessageResponseTimeToEnd();
  MessageResponseTimeToEnd::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageResponseTimeToEnd_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageResponseTimeToEnd_2eproto_once_);
void protobuf_AddDesc_MessageResponseTimeToEnd_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageResponseTimeToEnd_2eproto_once_,
                 &protobuf_AddDesc_MessageResponseTimeToEnd_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageResponseTimeToEnd_2eproto {
  StaticDescriptorInitializer_MessageResponseTimeToEnd_2eproto() {
    protobuf_AddDesc_MessageResponseTimeToEnd_2eproto();
  }
} static_descriptor_initializer_MessageResponseTimeToEnd_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageResponseTimeToEnd(
    MessageResponseTimeToEnd* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageResponseTimeToEnd::kRoomIdFieldNumber;
const int MessageResponseTimeToEnd::kGameWinnerFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageResponseTimeToEnd::MessageResponseTimeToEnd()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageResponseTimeToEnd)
}

void MessageResponseTimeToEnd::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  gamewinner_ = const_cast< ::MessageResponseRoundPlayerBang*>(
      ::MessageResponseRoundPlayerBang::internal_default_instance());
#else
  gamewinner_ = const_cast< ::MessageResponseRoundPlayerBang*>(&::MessageResponseRoundPlayerBang::default_instance());
#endif
}

MessageResponseTimeToEnd::MessageResponseTimeToEnd(const MessageResponseTimeToEnd& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageResponseTimeToEnd)
}

void MessageResponseTimeToEnd::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  roomid_ = GOOGLE_LONGLONG(0);
  gamewinner_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageResponseTimeToEnd::~MessageResponseTimeToEnd() {
  // @@protoc_insertion_point(destructor:MessageResponseTimeToEnd)
  SharedDtor();
}

void MessageResponseTimeToEnd::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete gamewinner_;
  }
}

void MessageResponseTimeToEnd::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageResponseTimeToEnd& MessageResponseTimeToEnd::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageResponseTimeToEnd_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageResponseTimeToEnd_2eproto();
#endif
  return *default_instance_;
}

MessageResponseTimeToEnd* MessageResponseTimeToEnd::default_instance_ = NULL;

MessageResponseTimeToEnd* MessageResponseTimeToEnd::New(::google::protobuf::Arena* arena) const {
  MessageResponseTimeToEnd* n = new MessageResponseTimeToEnd;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageResponseTimeToEnd::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageResponseTimeToEnd)
  if (_has_bits_[0 / 32] & 3u) {
    roomid_ = GOOGLE_LONGLONG(0);
    if (has_gamewinner()) {
      if (gamewinner_ != NULL) gamewinner_->::MessageResponseRoundPlayerBang::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageResponseTimeToEnd::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageResponseTimeToEnd, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageResponseTimeToEnd)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 roomId = 1 [default = 0];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &roomid_)));
          set_has_roomid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_gameWinner;
        break;
      }

      // optional .MessageResponseRoundPlayerBang gameWinner = 2;
      case 2: {
        if (tag == 18) {
         parse_gameWinner:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_gamewinner()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageResponseTimeToEnd)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageResponseTimeToEnd)
  return false;
#undef DO_
}

void MessageResponseTimeToEnd::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageResponseTimeToEnd)
  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->roomid(), output);
  }

  // optional .MessageResponseRoundPlayerBang gameWinner = 2;
  if (has_gamewinner()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->gamewinner_, output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageResponseTimeToEnd)
}

int MessageResponseTimeToEnd::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageResponseTimeToEnd)
  int total_size = 0;

  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());
  }
  // optional .MessageResponseRoundPlayerBang gameWinner = 2;
  if (has_gamewinner()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->gamewinner_);
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageResponseTimeToEnd::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageResponseTimeToEnd*>(&from));
}

void MessageResponseTimeToEnd::MergeFrom(const MessageResponseTimeToEnd& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageResponseTimeToEnd)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_roomid()) {
      set_roomid(from.roomid());
    }
    if (from.has_gamewinner()) {
      mutable_gamewinner()->::MessageResponseRoundPlayerBang::MergeFrom(from.gamewinner());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageResponseTimeToEnd::CopyFrom(const MessageResponseTimeToEnd& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageResponseTimeToEnd)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageResponseTimeToEnd::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (has_gamewinner()) {
    if (!this->gamewinner_->IsInitialized()) return false;
  }
  return true;
}

void MessageResponseTimeToEnd::Swap(MessageResponseTimeToEnd* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageResponseTimeToEnd::InternalSwap(MessageResponseTimeToEnd* other) {
  std::swap(roomid_, other->roomid_);
  std::swap(gamewinner_, other->gamewinner_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageResponseTimeToEnd::GetTypeName() const {
  return "MessageResponseTimeToEnd";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseTimeToEnd

// required int64 roomId = 1 [default = 0];
bool MessageResponseTimeToEnd::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageResponseTimeToEnd::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageResponseTimeToEnd::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageResponseTimeToEnd::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
 ::google::protobuf::int64 MessageResponseTimeToEnd::roomid() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToEnd.roomId)
  return roomid_;
}
 void MessageResponseTimeToEnd::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToEnd.roomId)
}

// optional .MessageResponseRoundPlayerBang gameWinner = 2;
bool MessageResponseTimeToEnd::has_gamewinner() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MessageResponseTimeToEnd::set_has_gamewinner() {
  _has_bits_[0] |= 0x00000002u;
}
void MessageResponseTimeToEnd::clear_has_gamewinner() {
  _has_bits_[0] &= ~0x00000002u;
}
void MessageResponseTimeToEnd::clear_gamewinner() {
  if (gamewinner_ != NULL) gamewinner_->::MessageResponseRoundPlayerBang::Clear();
  clear_has_gamewinner();
}
const ::MessageResponseRoundPlayerBang& MessageResponseTimeToEnd::gamewinner() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToEnd.gameWinner)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return gamewinner_ != NULL ? *gamewinner_ : *default_instance().gamewinner_;
#else
  return gamewinner_ != NULL ? *gamewinner_ : *default_instance_->gamewinner_;
#endif
}
::MessageResponseRoundPlayerBang* MessageResponseTimeToEnd::mutable_gamewinner() {
  set_has_gamewinner();
  if (gamewinner_ == NULL) {
    gamewinner_ = new ::MessageResponseRoundPlayerBang;
  }
  // @@protoc_insertion_point(field_mutable:MessageResponseTimeToEnd.gameWinner)
  return gamewinner_;
}
::MessageResponseRoundPlayerBang* MessageResponseTimeToEnd::release_gamewinner() {
  // @@protoc_insertion_point(field_release:MessageResponseTimeToEnd.gameWinner)
  clear_has_gamewinner();
  ::MessageResponseRoundPlayerBang* temp = gamewinner_;
  gamewinner_ = NULL;
  return temp;
}
void MessageResponseTimeToEnd::set_allocated_gamewinner(::MessageResponseRoundPlayerBang* gamewinner) {
  delete gamewinner_;
  gamewinner_ = gamewinner;
  if (gamewinner) {
    set_has_gamewinner();
  } else {
    clear_has_gamewinner();
  }
  // @@protoc_insertion_point(field_set_allocated:MessageResponseTimeToEnd.gameWinner)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
