// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseRoundPlayerDuelist.proto

#ifndef PROTOBUF_MessageResponseRoundPlayerDuelist_2eproto__INCLUDED
#define PROTOBUF_MessageResponseRoundPlayerDuelist_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MessageResponseRoundPlayerDuelist_2eproto();
void protobuf_AssignDesc_MessageResponseRoundPlayerDuelist_2eproto();
void protobuf_ShutdownFile_MessageResponseRoundPlayerDuelist_2eproto();

class MessageResponseRoundPlayerDuelist;

// ===================================================================

class MessageResponseRoundPlayerDuelist : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:MessageResponseRoundPlayerDuelist) */ {
 public:
  MessageResponseRoundPlayerDuelist();
  virtual ~MessageResponseRoundPlayerDuelist();

  MessageResponseRoundPlayerDuelist(const MessageResponseRoundPlayerDuelist& from);

  inline MessageResponseRoundPlayerDuelist& operator=(const MessageResponseRoundPlayerDuelist& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const MessageResponseRoundPlayerDuelist& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MessageResponseRoundPlayerDuelist* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MessageResponseRoundPlayerDuelist* other);

  // implements Message ----------------------------------------------

  inline MessageResponseRoundPlayerDuelist* New() const { return New(NULL); }

  MessageResponseRoundPlayerDuelist* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MessageResponseRoundPlayerDuelist& from);
  void MergeFrom(const MessageResponseRoundPlayerDuelist& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageResponseRoundPlayerDuelist* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 playerId = 1 [default = 0];
  bool has_playerid() const;
  void clear_playerid();
  static const int kPlayerIdFieldNumber = 1;
  ::google::protobuf::int64 playerid() const;
  void set_playerid(::google::protobuf::int64 value);

  // required int32 playerPosition = 2 [default = 0];
  bool has_playerposition() const;
  void clear_playerposition();
  static const int kPlayerPositionFieldNumber = 2;
  ::google::protobuf::int32 playerposition() const;
  void set_playerposition(::google::protobuf::int32 value);

  // required bool playerIsDuelist = 3 [default = false];
  bool has_playerisduelist() const;
  void clear_playerisduelist();
  static const int kPlayerIsDuelistFieldNumber = 3;
  bool playerisduelist() const;
  void set_playerisduelist(bool value);

  // required int32 winAmount = 4 [default = 0];
  bool has_winamount() const;
  void clear_winamount();
  static const int kWinAmountFieldNumber = 4;
  ::google::protobuf::int32 winamount() const;
  void set_winamount(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MessageResponseRoundPlayerDuelist)
 private:
  inline void set_has_playerid();
  inline void clear_has_playerid();
  inline void set_has_playerposition();
  inline void clear_has_playerposition();
  inline void set_has_playerisduelist();
  inline void clear_has_playerisduelist();
  inline void set_has_winamount();
  inline void clear_has_winamount();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 playerid_;
  ::google::protobuf::int32 playerposition_;
  bool playerisduelist_;
  ::google::protobuf::int32 winamount_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MessageResponseRoundPlayerDuelist_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MessageResponseRoundPlayerDuelist_2eproto();
  #endif
  friend void protobuf_AssignDesc_MessageResponseRoundPlayerDuelist_2eproto();
  friend void protobuf_ShutdownFile_MessageResponseRoundPlayerDuelist_2eproto();

  void InitAsDefaultInstance();
  static MessageResponseRoundPlayerDuelist* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseRoundPlayerDuelist

// required int64 playerId = 1 [default = 0];
inline bool MessageResponseRoundPlayerDuelist::has_playerid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageResponseRoundPlayerDuelist::set_has_playerid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageResponseRoundPlayerDuelist::clear_has_playerid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageResponseRoundPlayerDuelist::clear_playerid() {
  playerid_ = GOOGLE_LONGLONG(0);
  clear_has_playerid();
}
inline ::google::protobuf::int64 MessageResponseRoundPlayerDuelist::playerid() const {
  // @@protoc_insertion_point(field_get:MessageResponseRoundPlayerDuelist.playerId)
  return playerid_;
}
inline void MessageResponseRoundPlayerDuelist::set_playerid(::google::protobuf::int64 value) {
  set_has_playerid();
  playerid_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseRoundPlayerDuelist.playerId)
}

// required int32 playerPosition = 2 [default = 0];
inline bool MessageResponseRoundPlayerDuelist::has_playerposition() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageResponseRoundPlayerDuelist::set_has_playerposition() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageResponseRoundPlayerDuelist::clear_has_playerposition() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageResponseRoundPlayerDuelist::clear_playerposition() {
  playerposition_ = 0;
  clear_has_playerposition();
}
inline ::google::protobuf::int32 MessageResponseRoundPlayerDuelist::playerposition() const {
  // @@protoc_insertion_point(field_get:MessageResponseRoundPlayerDuelist.playerPosition)
  return playerposition_;
}
inline void MessageResponseRoundPlayerDuelist::set_playerposition(::google::protobuf::int32 value) {
  set_has_playerposition();
  playerposition_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseRoundPlayerDuelist.playerPosition)
}

// required bool playerIsDuelist = 3 [default = false];
inline bool MessageResponseRoundPlayerDuelist::has_playerisduelist() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageResponseRoundPlayerDuelist::set_has_playerisduelist() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageResponseRoundPlayerDuelist::clear_has_playerisduelist() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageResponseRoundPlayerDuelist::clear_playerisduelist() {
  playerisduelist_ = false;
  clear_has_playerisduelist();
}
inline bool MessageResponseRoundPlayerDuelist::playerisduelist() const {
  // @@protoc_insertion_point(field_get:MessageResponseRoundPlayerDuelist.playerIsDuelist)
  return playerisduelist_;
}
inline void MessageResponseRoundPlayerDuelist::set_playerisduelist(bool value) {
  set_has_playerisduelist();
  playerisduelist_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseRoundPlayerDuelist.playerIsDuelist)
}

// required int32 winAmount = 4 [default = 0];
inline bool MessageResponseRoundPlayerDuelist::has_winamount() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageResponseRoundPlayerDuelist::set_has_winamount() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageResponseRoundPlayerDuelist::clear_has_winamount() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageResponseRoundPlayerDuelist::clear_winamount() {
  winamount_ = 0;
  clear_has_winamount();
}
inline ::google::protobuf::int32 MessageResponseRoundPlayerDuelist::winamount() const {
  // @@protoc_insertion_point(field_get:MessageResponseRoundPlayerDuelist.winAmount)
  return winamount_;
}
inline void MessageResponseRoundPlayerDuelist::set_winamount(::google::protobuf::int32 value) {
  set_has_winamount();
  winamount_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseRoundPlayerDuelist.winAmount)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageResponseRoundPlayerDuelist_2eproto__INCLUDED
