// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseTimeToResults.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageResponseTimeToResults.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageResponseTimeToResults_2eproto() {
  delete MessageResponseTimeToResults::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageResponseTimeToResults_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageResponseTimeToResults_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::protobuf_AddDesc_MessageResponseRoundPlayerBang_2eproto();
  ::protobuf_AddDesc_MessageResponseRoundPlayerDuelist_2eproto();
  MessageResponseTimeToResults::default_instance_ = new MessageResponseTimeToResults();
  MessageResponseTimeToResults::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageResponseTimeToResults_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageResponseTimeToResults_2eproto_once_);
void protobuf_AddDesc_MessageResponseTimeToResults_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageResponseTimeToResults_2eproto_once_,
                 &protobuf_AddDesc_MessageResponseTimeToResults_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageResponseTimeToResults_2eproto {
  StaticDescriptorInitializer_MessageResponseTimeToResults_2eproto() {
    protobuf_AddDesc_MessageResponseTimeToResults_2eproto();
  }
} static_descriptor_initializer_MessageResponseTimeToResults_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageResponseTimeToResults(
    MessageResponseTimeToResults* ptr) {
  return ptr->mutable_unknown_fields();
}

bool MessageResponseTimeToResults_eRoomResultType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const MessageResponseTimeToResults_eRoomResultType MessageResponseTimeToResults::rrtPlayerBang;
const MessageResponseTimeToResults_eRoomResultType MessageResponseTimeToResults::rrtPlayerDuelist;
const MessageResponseTimeToResults_eRoomResultType MessageResponseTimeToResults::eRoomResultType_MIN;
const MessageResponseTimeToResults_eRoomResultType MessageResponseTimeToResults::eRoomResultType_MAX;
const int MessageResponseTimeToResults::eRoomResultType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageResponseTimeToResults::kRoomIdFieldNumber;
const int MessageResponseTimeToResults::kTimeFieldNumber;
const int MessageResponseTimeToResults::kResultTypeFieldNumber;
const int MessageResponseTimeToResults::kGameResultsFieldNumber;
const int MessageResponseTimeToResults::kDuelistResultsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageResponseTimeToResults::MessageResponseTimeToResults()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageResponseTimeToResults)
}

void MessageResponseTimeToResults::InitAsDefaultInstance() {
}

MessageResponseTimeToResults::MessageResponseTimeToResults(const MessageResponseTimeToResults& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageResponseTimeToResults)
}

void MessageResponseTimeToResults::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  roomid_ = GOOGLE_LONGLONG(0);
  time_ = 0;
  resulttype_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageResponseTimeToResults::~MessageResponseTimeToResults() {
  // @@protoc_insertion_point(destructor:MessageResponseTimeToResults)
  SharedDtor();
}

void MessageResponseTimeToResults::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MessageResponseTimeToResults::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageResponseTimeToResults& MessageResponseTimeToResults::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageResponseTimeToResults_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageResponseTimeToResults_2eproto();
#endif
  return *default_instance_;
}

MessageResponseTimeToResults* MessageResponseTimeToResults::default_instance_ = NULL;

MessageResponseTimeToResults* MessageResponseTimeToResults::New(::google::protobuf::Arena* arena) const {
  MessageResponseTimeToResults* n = new MessageResponseTimeToResults;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageResponseTimeToResults::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageResponseTimeToResults)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MessageResponseTimeToResults, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MessageResponseTimeToResults*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(roomid_, resulttype_);

#undef ZR_HELPER_
#undef ZR_

  gameresults_.Clear();
  duelistresults_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageResponseTimeToResults::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageResponseTimeToResults, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageResponseTimeToResults)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 roomId = 1 [default = 0];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &roomid_)));
          set_has_roomid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_time;
        break;
      }

      // required int32 time = 2 [default = 0];
      case 2: {
        if (tag == 16) {
         parse_time:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &time_)));
          set_has_time();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_resultType;
        break;
      }

      // required .MessageResponseTimeToResults.eRoomResultType resultType = 3 [default = rrtPlayerBang];
      case 3: {
        if (tag == 24) {
         parse_resultType:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MessageResponseTimeToResults_eRoomResultType_IsValid(value)) {
            set_resulttype(static_cast< ::MessageResponseTimeToResults_eRoomResultType >(value));
          } else {
            unknown_fields_stream.WriteVarint32(24);
            unknown_fields_stream.WriteVarint32(value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_gameResults;
        break;
      }

      // repeated .MessageResponseRoundPlayerBang gameResults = 4;
      case 4: {
        if (tag == 34) {
         parse_gameResults:
          DO_(input->IncrementRecursionDepth());
         parse_loop_gameResults:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_gameresults()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_loop_gameResults;
        if (input->ExpectTag(42)) goto parse_loop_duelistResults;
        input->UnsafeDecrementRecursionDepth();
        break;
      }

      // repeated .MessageResponseRoundPlayerDuelist duelistResults = 5;
      case 5: {
        if (tag == 42) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_duelistResults:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_duelistresults()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_loop_duelistResults;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageResponseTimeToResults)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageResponseTimeToResults)
  return false;
#undef DO_
}

void MessageResponseTimeToResults::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageResponseTimeToResults)
  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->roomid(), output);
  }

  // required int32 time = 2 [default = 0];
  if (has_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->time(), output);
  }

  // required .MessageResponseTimeToResults.eRoomResultType resultType = 3 [default = rrtPlayerBang];
  if (has_resulttype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      3, this->resulttype(), output);
  }

  // repeated .MessageResponseRoundPlayerBang gameResults = 4;
  for (unsigned int i = 0, n = this->gameresults_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      4, this->gameresults(i), output);
  }

  // repeated .MessageResponseRoundPlayerDuelist duelistResults = 5;
  for (unsigned int i = 0, n = this->duelistresults_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      5, this->duelistresults(i), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageResponseTimeToResults)
}

int MessageResponseTimeToResults::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MessageResponseTimeToResults)
  int total_size = 0;

  if (has_roomid()) {
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());
  }

  if (has_time()) {
    // required int32 time = 2 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->time());
  }

  if (has_resulttype()) {
    // required .MessageResponseTimeToResults.eRoomResultType resultType = 3 [default = rrtPlayerBang];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->resulttype());
  }

  return total_size;
}
int MessageResponseTimeToResults::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageResponseTimeToResults)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());

    // required int32 time = 2 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->time());

    // required .MessageResponseTimeToResults.eRoomResultType resultType = 3 [default = rrtPlayerBang];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->resulttype());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  // repeated .MessageResponseRoundPlayerBang gameResults = 4;
  total_size += 1 * this->gameresults_size();
  for (int i = 0; i < this->gameresults_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->gameresults(i));
  }

  // repeated .MessageResponseRoundPlayerDuelist duelistResults = 5;
  total_size += 1 * this->duelistresults_size();
  for (int i = 0; i < this->duelistresults_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->duelistresults(i));
  }

  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageResponseTimeToResults::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageResponseTimeToResults*>(&from));
}

void MessageResponseTimeToResults::MergeFrom(const MessageResponseTimeToResults& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageResponseTimeToResults)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  gameresults_.MergeFrom(from.gameresults_);
  duelistresults_.MergeFrom(from.duelistresults_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_roomid()) {
      set_roomid(from.roomid());
    }
    if (from.has_time()) {
      set_time(from.time());
    }
    if (from.has_resulttype()) {
      set_resulttype(from.resulttype());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageResponseTimeToResults::CopyFrom(const MessageResponseTimeToResults& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageResponseTimeToResults)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageResponseTimeToResults::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000007) != 0x00000007) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->gameresults())) return false;
  if (!::google::protobuf::internal::AllAreInitialized(this->duelistresults())) return false;
  return true;
}

void MessageResponseTimeToResults::Swap(MessageResponseTimeToResults* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageResponseTimeToResults::InternalSwap(MessageResponseTimeToResults* other) {
  std::swap(roomid_, other->roomid_);
  std::swap(time_, other->time_);
  std::swap(resulttype_, other->resulttype_);
  gameresults_.UnsafeArenaSwap(&other->gameresults_);
  duelistresults_.UnsafeArenaSwap(&other->duelistresults_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageResponseTimeToResults::GetTypeName() const {
  return "MessageResponseTimeToResults";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseTimeToResults

// required int64 roomId = 1 [default = 0];
bool MessageResponseTimeToResults::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageResponseTimeToResults::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageResponseTimeToResults::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageResponseTimeToResults::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
 ::google::protobuf::int64 MessageResponseTimeToResults::roomid() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToResults.roomId)
  return roomid_;
}
 void MessageResponseTimeToResults::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToResults.roomId)
}

// required int32 time = 2 [default = 0];
bool MessageResponseTimeToResults::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MessageResponseTimeToResults::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
void MessageResponseTimeToResults::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
void MessageResponseTimeToResults::clear_time() {
  time_ = 0;
  clear_has_time();
}
 ::google::protobuf::int32 MessageResponseTimeToResults::time() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToResults.time)
  return time_;
}
 void MessageResponseTimeToResults::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToResults.time)
}

// required .MessageResponseTimeToResults.eRoomResultType resultType = 3 [default = rrtPlayerBang];
bool MessageResponseTimeToResults::has_resulttype() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void MessageResponseTimeToResults::set_has_resulttype() {
  _has_bits_[0] |= 0x00000004u;
}
void MessageResponseTimeToResults::clear_has_resulttype() {
  _has_bits_[0] &= ~0x00000004u;
}
void MessageResponseTimeToResults::clear_resulttype() {
  resulttype_ = 0;
  clear_has_resulttype();
}
 ::MessageResponseTimeToResults_eRoomResultType MessageResponseTimeToResults::resulttype() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToResults.resultType)
  return static_cast< ::MessageResponseTimeToResults_eRoomResultType >(resulttype_);
}
 void MessageResponseTimeToResults::set_resulttype(::MessageResponseTimeToResults_eRoomResultType value) {
  assert(::MessageResponseTimeToResults_eRoomResultType_IsValid(value));
  set_has_resulttype();
  resulttype_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToResults.resultType)
}

// repeated .MessageResponseRoundPlayerBang gameResults = 4;
int MessageResponseTimeToResults::gameresults_size() const {
  return gameresults_.size();
}
void MessageResponseTimeToResults::clear_gameresults() {
  gameresults_.Clear();
}
const ::MessageResponseRoundPlayerBang& MessageResponseTimeToResults::gameresults(int index) const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToResults.gameResults)
  return gameresults_.Get(index);
}
::MessageResponseRoundPlayerBang* MessageResponseTimeToResults::mutable_gameresults(int index) {
  // @@protoc_insertion_point(field_mutable:MessageResponseTimeToResults.gameResults)
  return gameresults_.Mutable(index);
}
::MessageResponseRoundPlayerBang* MessageResponseTimeToResults::add_gameresults() {
  // @@protoc_insertion_point(field_add:MessageResponseTimeToResults.gameResults)
  return gameresults_.Add();
}
::google::protobuf::RepeatedPtrField< ::MessageResponseRoundPlayerBang >*
MessageResponseTimeToResults::mutable_gameresults() {
  // @@protoc_insertion_point(field_mutable_list:MessageResponseTimeToResults.gameResults)
  return &gameresults_;
}
const ::google::protobuf::RepeatedPtrField< ::MessageResponseRoundPlayerBang >&
MessageResponseTimeToResults::gameresults() const {
  // @@protoc_insertion_point(field_list:MessageResponseTimeToResults.gameResults)
  return gameresults_;
}

// repeated .MessageResponseRoundPlayerDuelist duelistResults = 5;
int MessageResponseTimeToResults::duelistresults_size() const {
  return duelistresults_.size();
}
void MessageResponseTimeToResults::clear_duelistresults() {
  duelistresults_.Clear();
}
const ::MessageResponseRoundPlayerDuelist& MessageResponseTimeToResults::duelistresults(int index) const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToResults.duelistResults)
  return duelistresults_.Get(index);
}
::MessageResponseRoundPlayerDuelist* MessageResponseTimeToResults::mutable_duelistresults(int index) {
  // @@protoc_insertion_point(field_mutable:MessageResponseTimeToResults.duelistResults)
  return duelistresults_.Mutable(index);
}
::MessageResponseRoundPlayerDuelist* MessageResponseTimeToResults::add_duelistresults() {
  // @@protoc_insertion_point(field_add:MessageResponseTimeToResults.duelistResults)
  return duelistresults_.Add();
}
::google::protobuf::RepeatedPtrField< ::MessageResponseRoundPlayerDuelist >*
MessageResponseTimeToResults::mutable_duelistresults() {
  // @@protoc_insertion_point(field_mutable_list:MessageResponseTimeToResults.duelistResults)
  return &duelistresults_;
}
const ::google::protobuf::RepeatedPtrField< ::MessageResponseRoundPlayerDuelist >&
MessageResponseTimeToResults::duelistresults() const {
  // @@protoc_insertion_point(field_list:MessageResponseTimeToResults.duelistResults)
  return duelistresults_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
