// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseBuyShopItem.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageResponseBuyShopItem.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageResponseBuyShopItem_2eproto() {
  delete MessageResponseBuyShopItem::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageResponseBuyShopItem_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageResponseBuyShopItem_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  MessageResponseBuyShopItem::default_instance_ = new MessageResponseBuyShopItem();
  MessageResponseBuyShopItem::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageResponseBuyShopItem_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageResponseBuyShopItem_2eproto_once_);
void protobuf_AddDesc_MessageResponseBuyShopItem_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageResponseBuyShopItem_2eproto_once_,
                 &protobuf_AddDesc_MessageResponseBuyShopItem_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageResponseBuyShopItem_2eproto {
  StaticDescriptorInitializer_MessageResponseBuyShopItem_2eproto() {
    protobuf_AddDesc_MessageResponseBuyShopItem_2eproto();
  }
} static_descriptor_initializer_MessageResponseBuyShopItem_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageResponseBuyShopItem(
    MessageResponseBuyShopItem* ptr) {
  return ptr->mutable_unknown_fields();
}

bool MessageResponseBuyShopItem_eBuyErrorType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const MessageResponseBuyShopItem_eBuyErrorType MessageResponseBuyShopItem::betNone;
const MessageResponseBuyShopItem_eBuyErrorType MessageResponseBuyShopItem::betMoneyLessThenNeed;
const MessageResponseBuyShopItem_eBuyErrorType MessageResponseBuyShopItem::betReceiptError;
const MessageResponseBuyShopItem_eBuyErrorType MessageResponseBuyShopItem::betInternalError;
const MessageResponseBuyShopItem_eBuyErrorType MessageResponseBuyShopItem::eBuyErrorType_MIN;
const MessageResponseBuyShopItem_eBuyErrorType MessageResponseBuyShopItem::eBuyErrorType_MAX;
const int MessageResponseBuyShopItem::eBuyErrorType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageResponseBuyShopItem::kShopItemNameFieldNumber;
const int MessageResponseBuyShopItem::kBuyErrorTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageResponseBuyShopItem::MessageResponseBuyShopItem()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageResponseBuyShopItem)
}

void MessageResponseBuyShopItem::InitAsDefaultInstance() {
}

MessageResponseBuyShopItem::MessageResponseBuyShopItem(const MessageResponseBuyShopItem& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageResponseBuyShopItem)
}

void MessageResponseBuyShopItem::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  shopitemname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  buyerrortype_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageResponseBuyShopItem::~MessageResponseBuyShopItem() {
  // @@protoc_insertion_point(destructor:MessageResponseBuyShopItem)
  SharedDtor();
}

void MessageResponseBuyShopItem::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  shopitemname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MessageResponseBuyShopItem::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageResponseBuyShopItem& MessageResponseBuyShopItem::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageResponseBuyShopItem_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageResponseBuyShopItem_2eproto();
#endif
  return *default_instance_;
}

MessageResponseBuyShopItem* MessageResponseBuyShopItem::default_instance_ = NULL;

MessageResponseBuyShopItem* MessageResponseBuyShopItem::New(::google::protobuf::Arena* arena) const {
  MessageResponseBuyShopItem* n = new MessageResponseBuyShopItem;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageResponseBuyShopItem::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageResponseBuyShopItem)
  if (_has_bits_[0 / 32] & 3u) {
    if (has_shopitemname()) {
      shopitemname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    buyerrortype_ = 0;
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageResponseBuyShopItem::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageResponseBuyShopItem, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageResponseBuyShopItem)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string shopItemName = 1 [default = ""];
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_shopitemname()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_buyErrorType;
        break;
      }

      // required .MessageResponseBuyShopItem.eBuyErrorType buyErrorType = 2 [default = betNone];
      case 2: {
        if (tag == 16) {
         parse_buyErrorType:
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          if (::MessageResponseBuyShopItem_eBuyErrorType_IsValid(value)) {
            set_buyerrortype(static_cast< ::MessageResponseBuyShopItem_eBuyErrorType >(value));
          } else {
            unknown_fields_stream.WriteVarint32(16);
            unknown_fields_stream.WriteVarint32(value);
          }
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageResponseBuyShopItem)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageResponseBuyShopItem)
  return false;
#undef DO_
}

void MessageResponseBuyShopItem::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageResponseBuyShopItem)
  // required string shopItemName = 1 [default = ""];
  if (has_shopitemname()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->shopitemname(), output);
  }

  // required .MessageResponseBuyShopItem.eBuyErrorType buyErrorType = 2 [default = betNone];
  if (has_buyerrortype()) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      2, this->buyerrortype(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageResponseBuyShopItem)
}

int MessageResponseBuyShopItem::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MessageResponseBuyShopItem)
  int total_size = 0;

  if (has_shopitemname()) {
    // required string shopItemName = 1 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->shopitemname());
  }

  if (has_buyerrortype()) {
    // required .MessageResponseBuyShopItem.eBuyErrorType buyErrorType = 2 [default = betNone];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->buyerrortype());
  }

  return total_size;
}
int MessageResponseBuyShopItem::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageResponseBuyShopItem)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required string shopItemName = 1 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->shopitemname());

    // required .MessageResponseBuyShopItem.eBuyErrorType buyErrorType = 2 [default = betNone];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->buyerrortype());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageResponseBuyShopItem::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageResponseBuyShopItem*>(&from));
}

void MessageResponseBuyShopItem::MergeFrom(const MessageResponseBuyShopItem& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageResponseBuyShopItem)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_shopitemname()) {
      set_has_shopitemname();
      shopitemname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.shopitemname_);
    }
    if (from.has_buyerrortype()) {
      set_buyerrortype(from.buyerrortype());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageResponseBuyShopItem::CopyFrom(const MessageResponseBuyShopItem& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageResponseBuyShopItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageResponseBuyShopItem::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MessageResponseBuyShopItem::Swap(MessageResponseBuyShopItem* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageResponseBuyShopItem::InternalSwap(MessageResponseBuyShopItem* other) {
  shopitemname_.Swap(&other->shopitemname_);
  std::swap(buyerrortype_, other->buyerrortype_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageResponseBuyShopItem::GetTypeName() const {
  return "MessageResponseBuyShopItem";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseBuyShopItem

// required string shopItemName = 1 [default = ""];
bool MessageResponseBuyShopItem::has_shopitemname() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageResponseBuyShopItem::set_has_shopitemname() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageResponseBuyShopItem::clear_has_shopitemname() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageResponseBuyShopItem::clear_shopitemname() {
  shopitemname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shopitemname();
}
 const ::std::string& MessageResponseBuyShopItem::shopitemname() const {
  // @@protoc_insertion_point(field_get:MessageResponseBuyShopItem.shopItemName)
  return shopitemname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponseBuyShopItem::set_shopitemname(const ::std::string& value) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageResponseBuyShopItem.shopItemName)
}
 void MessageResponseBuyShopItem::set_shopitemname(const char* value) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageResponseBuyShopItem.shopItemName)
}
 void MessageResponseBuyShopItem::set_shopitemname(const char* value, size_t size) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageResponseBuyShopItem.shopItemName)
}
 ::std::string* MessageResponseBuyShopItem::mutable_shopitemname() {
  set_has_shopitemname();
  // @@protoc_insertion_point(field_mutable:MessageResponseBuyShopItem.shopItemName)
  return shopitemname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MessageResponseBuyShopItem::release_shopitemname() {
  // @@protoc_insertion_point(field_release:MessageResponseBuyShopItem.shopItemName)
  clear_has_shopitemname();
  return shopitemname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponseBuyShopItem::set_allocated_shopitemname(::std::string* shopitemname) {
  if (shopitemname != NULL) {
    set_has_shopitemname();
  } else {
    clear_has_shopitemname();
  }
  shopitemname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shopitemname);
  // @@protoc_insertion_point(field_set_allocated:MessageResponseBuyShopItem.shopItemName)
}

// required .MessageResponseBuyShopItem.eBuyErrorType buyErrorType = 2 [default = betNone];
bool MessageResponseBuyShopItem::has_buyerrortype() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MessageResponseBuyShopItem::set_has_buyerrortype() {
  _has_bits_[0] |= 0x00000002u;
}
void MessageResponseBuyShopItem::clear_has_buyerrortype() {
  _has_bits_[0] &= ~0x00000002u;
}
void MessageResponseBuyShopItem::clear_buyerrortype() {
  buyerrortype_ = 0;
  clear_has_buyerrortype();
}
 ::MessageResponseBuyShopItem_eBuyErrorType MessageResponseBuyShopItem::buyerrortype() const {
  // @@protoc_insertion_point(field_get:MessageResponseBuyShopItem.buyErrorType)
  return static_cast< ::MessageResponseBuyShopItem_eBuyErrorType >(buyerrortype_);
}
 void MessageResponseBuyShopItem::set_buyerrortype(::MessageResponseBuyShopItem_eBuyErrorType value) {
  assert(::MessageResponseBuyShopItem_eBuyErrorType_IsValid(value));
  set_has_buyerrortype();
  buyerrortype_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseBuyShopItem.buyErrorType)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
