// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRequestUsePlayerInventoryItem.proto

#ifndef PROTOBUF_MessageRequestUsePlayerInventoryItem_2eproto__INCLUDED
#define PROTOBUF_MessageRequestUsePlayerInventoryItem_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MessageRequestUsePlayerInventoryItem_2eproto();
void protobuf_AssignDesc_MessageRequestUsePlayerInventoryItem_2eproto();
void protobuf_ShutdownFile_MessageRequestUsePlayerInventoryItem_2eproto();

class MessageRequestUsePlayerInventoryItem;

// ===================================================================

class MessageRequestUsePlayerInventoryItem : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:MessageRequestUsePlayerInventoryItem) */ {
 public:
  MessageRequestUsePlayerInventoryItem();
  virtual ~MessageRequestUsePlayerInventoryItem();

  MessageRequestUsePlayerInventoryItem(const MessageRequestUsePlayerInventoryItem& from);

  inline MessageRequestUsePlayerInventoryItem& operator=(const MessageRequestUsePlayerInventoryItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const MessageRequestUsePlayerInventoryItem& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MessageRequestUsePlayerInventoryItem* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MessageRequestUsePlayerInventoryItem* other);

  // implements Message ----------------------------------------------

  inline MessageRequestUsePlayerInventoryItem* New() const { return New(NULL); }

  MessageRequestUsePlayerInventoryItem* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MessageRequestUsePlayerInventoryItem& from);
  void MergeFrom(const MessageRequestUsePlayerInventoryItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageRequestUsePlayerInventoryItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 roomId = 1 [default = 0];
  bool has_roomid() const;
  void clear_roomid();
  static const int kRoomIdFieldNumber = 1;
  ::google::protobuf::int64 roomid() const;
  void set_roomid(::google::protobuf::int64 value);

  // required int64 destPlayerId = 2 [default = 0];
  bool has_destplayerid() const;
  void clear_destplayerid();
  static const int kDestPlayerIdFieldNumber = 2;
  ::google::protobuf::int64 destplayerid() const;
  void set_destplayerid(::google::protobuf::int64 value);

  // required string shopItemName = 3 [default = ""];
  bool has_shopitemname() const;
  void clear_shopitemname();
  static const int kShopItemNameFieldNumber = 3;
  const ::std::string& shopitemname() const;
  void set_shopitemname(const ::std::string& value);
  void set_shopitemname(const char* value);
  void set_shopitemname(const char* value, size_t size);
  ::std::string* mutable_shopitemname();
  ::std::string* release_shopitemname();
  void set_allocated_shopitemname(::std::string* shopitemname);

  // @@protoc_insertion_point(class_scope:MessageRequestUsePlayerInventoryItem)
 private:
  inline void set_has_roomid();
  inline void clear_has_roomid();
  inline void set_has_destplayerid();
  inline void clear_has_destplayerid();
  inline void set_has_shopitemname();
  inline void clear_has_shopitemname();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 roomid_;
  ::google::protobuf::int64 destplayerid_;
  ::google::protobuf::internal::ArenaStringPtr shopitemname_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MessageRequestUsePlayerInventoryItem_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MessageRequestUsePlayerInventoryItem_2eproto();
  #endif
  friend void protobuf_AssignDesc_MessageRequestUsePlayerInventoryItem_2eproto();
  friend void protobuf_ShutdownFile_MessageRequestUsePlayerInventoryItem_2eproto();

  void InitAsDefaultInstance();
  static MessageRequestUsePlayerInventoryItem* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageRequestUsePlayerInventoryItem

// required int64 roomId = 1 [default = 0];
inline bool MessageRequestUsePlayerInventoryItem::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageRequestUsePlayerInventoryItem::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageRequestUsePlayerInventoryItem::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageRequestUsePlayerInventoryItem::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
inline ::google::protobuf::int64 MessageRequestUsePlayerInventoryItem::roomid() const {
  // @@protoc_insertion_point(field_get:MessageRequestUsePlayerInventoryItem.roomId)
  return roomid_;
}
inline void MessageRequestUsePlayerInventoryItem::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestUsePlayerInventoryItem.roomId)
}

// required int64 destPlayerId = 2 [default = 0];
inline bool MessageRequestUsePlayerInventoryItem::has_destplayerid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageRequestUsePlayerInventoryItem::set_has_destplayerid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageRequestUsePlayerInventoryItem::clear_has_destplayerid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageRequestUsePlayerInventoryItem::clear_destplayerid() {
  destplayerid_ = GOOGLE_LONGLONG(0);
  clear_has_destplayerid();
}
inline ::google::protobuf::int64 MessageRequestUsePlayerInventoryItem::destplayerid() const {
  // @@protoc_insertion_point(field_get:MessageRequestUsePlayerInventoryItem.destPlayerId)
  return destplayerid_;
}
inline void MessageRequestUsePlayerInventoryItem::set_destplayerid(::google::protobuf::int64 value) {
  set_has_destplayerid();
  destplayerid_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestUsePlayerInventoryItem.destPlayerId)
}

// required string shopItemName = 3 [default = ""];
inline bool MessageRequestUsePlayerInventoryItem::has_shopitemname() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageRequestUsePlayerInventoryItem::set_has_shopitemname() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageRequestUsePlayerInventoryItem::clear_has_shopitemname() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageRequestUsePlayerInventoryItem::clear_shopitemname() {
  shopitemname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shopitemname();
}
inline const ::std::string& MessageRequestUsePlayerInventoryItem::shopitemname() const {
  // @@protoc_insertion_point(field_get:MessageRequestUsePlayerInventoryItem.shopItemName)
  return shopitemname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageRequestUsePlayerInventoryItem::set_shopitemname(const ::std::string& value) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageRequestUsePlayerInventoryItem.shopItemName)
}
inline void MessageRequestUsePlayerInventoryItem::set_shopitemname(const char* value) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageRequestUsePlayerInventoryItem.shopItemName)
}
inline void MessageRequestUsePlayerInventoryItem::set_shopitemname(const char* value, size_t size) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageRequestUsePlayerInventoryItem.shopItemName)
}
inline ::std::string* MessageRequestUsePlayerInventoryItem::mutable_shopitemname() {
  set_has_shopitemname();
  // @@protoc_insertion_point(field_mutable:MessageRequestUsePlayerInventoryItem.shopItemName)
  return shopitemname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageRequestUsePlayerInventoryItem::release_shopitemname() {
  // @@protoc_insertion_point(field_release:MessageRequestUsePlayerInventoryItem.shopItemName)
  clear_has_shopitemname();
  return shopitemname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageRequestUsePlayerInventoryItem::set_allocated_shopitemname(::std::string* shopitemname) {
  if (shopitemname != NULL) {
    set_has_shopitemname();
  } else {
    clear_has_shopitemname();
  }
  shopitemname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shopitemname);
  // @@protoc_insertion_point(field_set_allocated:MessageRequestUsePlayerInventoryItem.shopItemName)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageRequestUsePlayerInventoryItem_2eproto__INCLUDED
