// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseTimeToPutBullets.proto

#ifndef PROTOBUF_MessageResponseTimeToPutBullets_2eproto__INCLUDED
#define PROTOBUF_MessageResponseTimeToPutBullets_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MessageResponseTimeToPutBullets_2eproto();
void protobuf_AssignDesc_MessageResponseTimeToPutBullets_2eproto();
void protobuf_ShutdownFile_MessageResponseTimeToPutBullets_2eproto();

class MessageResponseTimeToPutBullets;

// ===================================================================

class MessageResponseTimeToPutBullets : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:MessageResponseTimeToPutBullets) */ {
 public:
  MessageResponseTimeToPutBullets();
  virtual ~MessageResponseTimeToPutBullets();

  MessageResponseTimeToPutBullets(const MessageResponseTimeToPutBullets& from);

  inline MessageResponseTimeToPutBullets& operator=(const MessageResponseTimeToPutBullets& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const MessageResponseTimeToPutBullets& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MessageResponseTimeToPutBullets* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MessageResponseTimeToPutBullets* other);

  // implements Message ----------------------------------------------

  inline MessageResponseTimeToPutBullets* New() const { return New(NULL); }

  MessageResponseTimeToPutBullets* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MessageResponseTimeToPutBullets& from);
  void MergeFrom(const MessageResponseTimeToPutBullets& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageResponseTimeToPutBullets* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 roomId = 1 [default = 0];
  bool has_roomid() const;
  void clear_roomid();
  static const int kRoomIdFieldNumber = 1;
  ::google::protobuf::int64 roomid() const;
  void set_roomid(::google::protobuf::int64 value);

  // required int32 time = 2 [default = 0];
  bool has_time() const;
  void clear_time();
  static const int kTimeFieldNumber = 2;
  ::google::protobuf::int32 time() const;
  void set_time(::google::protobuf::int32 value);

  // required int32 possibleBullets = 3 [default = 0];
  bool has_possiblebullets() const;
  void clear_possiblebullets();
  static const int kPossibleBulletsFieldNumber = 3;
  ::google::protobuf::int32 possiblebullets() const;
  void set_possiblebullets(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MessageResponseTimeToPutBullets)
 private:
  inline void set_has_roomid();
  inline void clear_has_roomid();
  inline void set_has_time();
  inline void clear_has_time();
  inline void set_has_possiblebullets();
  inline void clear_has_possiblebullets();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 roomid_;
  ::google::protobuf::int32 time_;
  ::google::protobuf::int32 possiblebullets_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MessageResponseTimeToPutBullets_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MessageResponseTimeToPutBullets_2eproto();
  #endif
  friend void protobuf_AssignDesc_MessageResponseTimeToPutBullets_2eproto();
  friend void protobuf_ShutdownFile_MessageResponseTimeToPutBullets_2eproto();

  void InitAsDefaultInstance();
  static MessageResponseTimeToPutBullets* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseTimeToPutBullets

// required int64 roomId = 1 [default = 0];
inline bool MessageResponseTimeToPutBullets::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageResponseTimeToPutBullets::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageResponseTimeToPutBullets::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageResponseTimeToPutBullets::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
inline ::google::protobuf::int64 MessageResponseTimeToPutBullets::roomid() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToPutBullets.roomId)
  return roomid_;
}
inline void MessageResponseTimeToPutBullets::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToPutBullets.roomId)
}

// required int32 time = 2 [default = 0];
inline bool MessageResponseTimeToPutBullets::has_time() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageResponseTimeToPutBullets::set_has_time() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageResponseTimeToPutBullets::clear_has_time() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageResponseTimeToPutBullets::clear_time() {
  time_ = 0;
  clear_has_time();
}
inline ::google::protobuf::int32 MessageResponseTimeToPutBullets::time() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToPutBullets.time)
  return time_;
}
inline void MessageResponseTimeToPutBullets::set_time(::google::protobuf::int32 value) {
  set_has_time();
  time_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToPutBullets.time)
}

// required int32 possibleBullets = 3 [default = 0];
inline bool MessageResponseTimeToPutBullets::has_possiblebullets() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageResponseTimeToPutBullets::set_has_possiblebullets() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageResponseTimeToPutBullets::clear_has_possiblebullets() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageResponseTimeToPutBullets::clear_possiblebullets() {
  possiblebullets_ = 0;
  clear_has_possiblebullets();
}
inline ::google::protobuf::int32 MessageResponseTimeToPutBullets::possiblebullets() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToPutBullets.possibleBullets)
  return possiblebullets_;
}
inline void MessageResponseTimeToPutBullets::set_possiblebullets(::google::protobuf::int32 value) {
  set_has_possiblebullets();
  possiblebullets_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToPutBullets.possibleBullets)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageResponseTimeToPutBullets_2eproto__INCLUDED
