// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponsePlayerProfile.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageResponsePlayerProfile.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageResponsePlayerProfile_2eproto() {
  delete MessageResponsePlayerProfile::default_instance_;
  delete MessageResponsePlayerProfile::_default_playeravatar_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageResponsePlayerProfile_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageResponsePlayerProfile_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  MessageResponsePlayerProfile::_default_playeravatar_ =
      new ::std::string("\000", 1);
  MessageResponsePlayerProfile::default_instance_ = new MessageResponsePlayerProfile();
  MessageResponsePlayerProfile::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageResponsePlayerProfile_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageResponsePlayerProfile_2eproto_once_);
void protobuf_AddDesc_MessageResponsePlayerProfile_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageResponsePlayerProfile_2eproto_once_,
                 &protobuf_AddDesc_MessageResponsePlayerProfile_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageResponsePlayerProfile_2eproto {
  StaticDescriptorInitializer_MessageResponsePlayerProfile_2eproto() {
    protobuf_AddDesc_MessageResponsePlayerProfile_2eproto();
  }
} static_descriptor_initializer_MessageResponsePlayerProfile_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageResponsePlayerProfile(
    MessageResponsePlayerProfile* ptr) {
  return ptr->mutable_unknown_fields();
}

::std::string* MessageResponsePlayerProfile::_default_playeravatar_ = NULL;
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageResponsePlayerProfile::kPlayerNameFieldNumber;
const int MessageResponsePlayerProfile::kPlayerEmailFieldNumber;
const int MessageResponsePlayerProfile::kPlayerMoneyFieldNumber;
const int MessageResponsePlayerProfile::kPlayerAvatarFieldNumber;
const int MessageResponsePlayerProfile::kPlayerWinsFieldNumber;
const int MessageResponsePlayerProfile::kPlayerLosesFieldNumber;
const int MessageResponsePlayerProfile::kPlayerRatingFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageResponsePlayerProfile::MessageResponsePlayerProfile()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageResponsePlayerProfile)
}

void MessageResponsePlayerProfile::InitAsDefaultInstance() {
}

MessageResponsePlayerProfile::MessageResponsePlayerProfile(const MessageResponsePlayerProfile& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageResponsePlayerProfile)
}

void MessageResponsePlayerProfile::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  playername_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  playeremail_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  playermoney_ = GOOGLE_LONGLONG(0);
  playeravatar_.UnsafeSetDefault(_default_playeravatar_);
  playerwins_ = 0;
  playerloses_ = 0;
  playerrating_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageResponsePlayerProfile::~MessageResponsePlayerProfile() {
  // @@protoc_insertion_point(destructor:MessageResponsePlayerProfile)
  SharedDtor();
}

void MessageResponsePlayerProfile::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  playername_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  playeremail_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  playeravatar_.DestroyNoArena(_default_playeravatar_);
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MessageResponsePlayerProfile::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageResponsePlayerProfile& MessageResponsePlayerProfile::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageResponsePlayerProfile_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageResponsePlayerProfile_2eproto();
#endif
  return *default_instance_;
}

MessageResponsePlayerProfile* MessageResponsePlayerProfile::default_instance_ = NULL;

MessageResponsePlayerProfile* MessageResponsePlayerProfile::New(::google::protobuf::Arena* arena) const {
  MessageResponsePlayerProfile* n = new MessageResponsePlayerProfile;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageResponsePlayerProfile::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageResponsePlayerProfile)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MessageResponsePlayerProfile, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MessageResponsePlayerProfile*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 127u) {
    ZR_(playerwins_, playerrating_);
    if (has_playername()) {
      playername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    if (has_playeremail()) {
      playeremail_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    }
    playermoney_ = GOOGLE_LONGLONG(0);
    if (has_playeravatar()) {
      playeravatar_.ClearToDefaultNoArena(_default_playeravatar_);
    }
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageResponsePlayerProfile::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageResponsePlayerProfile, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageResponsePlayerProfile)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string playerName = 1 [default = ""];
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_playername()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_playerEmail;
        break;
      }

      // required string playerEmail = 2 [default = ""];
      case 2: {
        if (tag == 18) {
         parse_playerEmail:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_playeremail()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_playerMoney;
        break;
      }

      // required int64 playerMoney = 3 [default = 0];
      case 3: {
        if (tag == 24) {
         parse_playerMoney:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &playermoney_)));
          set_has_playermoney();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_playerAvatar;
        break;
      }

      // required bytes playerAvatar = 4 [default = "\000"];
      case 4: {
        if (tag == 34) {
         parse_playerAvatar:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_playeravatar()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_playerWins;
        break;
      }

      // required int32 playerWins = 5 [default = 0];
      case 5: {
        if (tag == 40) {
         parse_playerWins:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &playerwins_)));
          set_has_playerwins();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_playerLoses;
        break;
      }

      // required int32 playerLoses = 6 [default = 0];
      case 6: {
        if (tag == 48) {
         parse_playerLoses:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &playerloses_)));
          set_has_playerloses();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_playerRating;
        break;
      }

      // required int32 playerRating = 7 [default = 0];
      case 7: {
        if (tag == 56) {
         parse_playerRating:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &playerrating_)));
          set_has_playerrating();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageResponsePlayerProfile)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageResponsePlayerProfile)
  return false;
#undef DO_
}

void MessageResponsePlayerProfile::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageResponsePlayerProfile)
  // required string playerName = 1 [default = ""];
  if (has_playername()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->playername(), output);
  }

  // required string playerEmail = 2 [default = ""];
  if (has_playeremail()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->playeremail(), output);
  }

  // required int64 playerMoney = 3 [default = 0];
  if (has_playermoney()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->playermoney(), output);
  }

  // required bytes playerAvatar = 4 [default = "\000"];
  if (has_playeravatar()) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      4, this->playeravatar(), output);
  }

  // required int32 playerWins = 5 [default = 0];
  if (has_playerwins()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->playerwins(), output);
  }

  // required int32 playerLoses = 6 [default = 0];
  if (has_playerloses()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->playerloses(), output);
  }

  // required int32 playerRating = 7 [default = 0];
  if (has_playerrating()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->playerrating(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageResponsePlayerProfile)
}

int MessageResponsePlayerProfile::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MessageResponsePlayerProfile)
  int total_size = 0;

  if (has_playername()) {
    // required string playerName = 1 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->playername());
  }

  if (has_playeremail()) {
    // required string playerEmail = 2 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->playeremail());
  }

  if (has_playermoney()) {
    // required int64 playerMoney = 3 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->playermoney());
  }

  if (has_playeravatar()) {
    // required bytes playerAvatar = 4 [default = "\000"];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->playeravatar());
  }

  if (has_playerwins()) {
    // required int32 playerWins = 5 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerwins());
  }

  if (has_playerloses()) {
    // required int32 playerLoses = 6 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerloses());
  }

  if (has_playerrating()) {
    // required int32 playerRating = 7 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerrating());
  }

  return total_size;
}
int MessageResponsePlayerProfile::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageResponsePlayerProfile)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000007f) ^ 0x0000007f) == 0) {  // All required fields are present.
    // required string playerName = 1 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->playername());

    // required string playerEmail = 2 [default = ""];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->playeremail());

    // required int64 playerMoney = 3 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->playermoney());

    // required bytes playerAvatar = 4 [default = "\000"];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->playeravatar());

    // required int32 playerWins = 5 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerwins());

    // required int32 playerLoses = 6 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerloses());

    // required int32 playerRating = 7 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerrating());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageResponsePlayerProfile::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageResponsePlayerProfile*>(&from));
}

void MessageResponsePlayerProfile::MergeFrom(const MessageResponsePlayerProfile& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageResponsePlayerProfile)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_playername()) {
      set_has_playername();
      playername_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.playername_);
    }
    if (from.has_playeremail()) {
      set_has_playeremail();
      playeremail_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.playeremail_);
    }
    if (from.has_playermoney()) {
      set_playermoney(from.playermoney());
    }
    if (from.has_playeravatar()) {
      set_has_playeravatar();
      playeravatar_.AssignWithDefault(_default_playeravatar_, from.playeravatar_);
    }
    if (from.has_playerwins()) {
      set_playerwins(from.playerwins());
    }
    if (from.has_playerloses()) {
      set_playerloses(from.playerloses());
    }
    if (from.has_playerrating()) {
      set_playerrating(from.playerrating());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageResponsePlayerProfile::CopyFrom(const MessageResponsePlayerProfile& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageResponsePlayerProfile)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageResponsePlayerProfile::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000007f) != 0x0000007f) return false;

  return true;
}

void MessageResponsePlayerProfile::Swap(MessageResponsePlayerProfile* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageResponsePlayerProfile::InternalSwap(MessageResponsePlayerProfile* other) {
  playername_.Swap(&other->playername_);
  playeremail_.Swap(&other->playeremail_);
  std::swap(playermoney_, other->playermoney_);
  playeravatar_.Swap(&other->playeravatar_);
  std::swap(playerwins_, other->playerwins_);
  std::swap(playerloses_, other->playerloses_);
  std::swap(playerrating_, other->playerrating_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageResponsePlayerProfile::GetTypeName() const {
  return "MessageResponsePlayerProfile";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponsePlayerProfile

// required string playerName = 1 [default = ""];
bool MessageResponsePlayerProfile::has_playername() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageResponsePlayerProfile::set_has_playername() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageResponsePlayerProfile::clear_has_playername() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageResponsePlayerProfile::clear_playername() {
  playername_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_playername();
}
 const ::std::string& MessageResponsePlayerProfile::playername() const {
  // @@protoc_insertion_point(field_get:MessageResponsePlayerProfile.playerName)
  return playername_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponsePlayerProfile::set_playername(const ::std::string& value) {
  set_has_playername();
  playername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageResponsePlayerProfile.playerName)
}
 void MessageResponsePlayerProfile::set_playername(const char* value) {
  set_has_playername();
  playername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageResponsePlayerProfile.playerName)
}
 void MessageResponsePlayerProfile::set_playername(const char* value, size_t size) {
  set_has_playername();
  playername_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageResponsePlayerProfile.playerName)
}
 ::std::string* MessageResponsePlayerProfile::mutable_playername() {
  set_has_playername();
  // @@protoc_insertion_point(field_mutable:MessageResponsePlayerProfile.playerName)
  return playername_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MessageResponsePlayerProfile::release_playername() {
  // @@protoc_insertion_point(field_release:MessageResponsePlayerProfile.playerName)
  clear_has_playername();
  return playername_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponsePlayerProfile::set_allocated_playername(::std::string* playername) {
  if (playername != NULL) {
    set_has_playername();
  } else {
    clear_has_playername();
  }
  playername_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), playername);
  // @@protoc_insertion_point(field_set_allocated:MessageResponsePlayerProfile.playerName)
}

// required string playerEmail = 2 [default = ""];
bool MessageResponsePlayerProfile::has_playeremail() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MessageResponsePlayerProfile::set_has_playeremail() {
  _has_bits_[0] |= 0x00000002u;
}
void MessageResponsePlayerProfile::clear_has_playeremail() {
  _has_bits_[0] &= ~0x00000002u;
}
void MessageResponsePlayerProfile::clear_playeremail() {
  playeremail_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_playeremail();
}
 const ::std::string& MessageResponsePlayerProfile::playeremail() const {
  // @@protoc_insertion_point(field_get:MessageResponsePlayerProfile.playerEmail)
  return playeremail_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponsePlayerProfile::set_playeremail(const ::std::string& value) {
  set_has_playeremail();
  playeremail_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageResponsePlayerProfile.playerEmail)
}
 void MessageResponsePlayerProfile::set_playeremail(const char* value) {
  set_has_playeremail();
  playeremail_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageResponsePlayerProfile.playerEmail)
}
 void MessageResponsePlayerProfile::set_playeremail(const char* value, size_t size) {
  set_has_playeremail();
  playeremail_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageResponsePlayerProfile.playerEmail)
}
 ::std::string* MessageResponsePlayerProfile::mutable_playeremail() {
  set_has_playeremail();
  // @@protoc_insertion_point(field_mutable:MessageResponsePlayerProfile.playerEmail)
  return playeremail_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MessageResponsePlayerProfile::release_playeremail() {
  // @@protoc_insertion_point(field_release:MessageResponsePlayerProfile.playerEmail)
  clear_has_playeremail();
  return playeremail_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageResponsePlayerProfile::set_allocated_playeremail(::std::string* playeremail) {
  if (playeremail != NULL) {
    set_has_playeremail();
  } else {
    clear_has_playeremail();
  }
  playeremail_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), playeremail);
  // @@protoc_insertion_point(field_set_allocated:MessageResponsePlayerProfile.playerEmail)
}

// required int64 playerMoney = 3 [default = 0];
bool MessageResponsePlayerProfile::has_playermoney() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void MessageResponsePlayerProfile::set_has_playermoney() {
  _has_bits_[0] |= 0x00000004u;
}
void MessageResponsePlayerProfile::clear_has_playermoney() {
  _has_bits_[0] &= ~0x00000004u;
}
void MessageResponsePlayerProfile::clear_playermoney() {
  playermoney_ = GOOGLE_LONGLONG(0);
  clear_has_playermoney();
}
 ::google::protobuf::int64 MessageResponsePlayerProfile::playermoney() const {
  // @@protoc_insertion_point(field_get:MessageResponsePlayerProfile.playerMoney)
  return playermoney_;
}
 void MessageResponsePlayerProfile::set_playermoney(::google::protobuf::int64 value) {
  set_has_playermoney();
  playermoney_ = value;
  // @@protoc_insertion_point(field_set:MessageResponsePlayerProfile.playerMoney)
}

// required bytes playerAvatar = 4 [default = "\000"];
bool MessageResponsePlayerProfile::has_playeravatar() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void MessageResponsePlayerProfile::set_has_playeravatar() {
  _has_bits_[0] |= 0x00000008u;
}
void MessageResponsePlayerProfile::clear_has_playeravatar() {
  _has_bits_[0] &= ~0x00000008u;
}
void MessageResponsePlayerProfile::clear_playeravatar() {
  playeravatar_.ClearToDefaultNoArena(_default_playeravatar_);
  clear_has_playeravatar();
}
 const ::std::string& MessageResponsePlayerProfile::playeravatar() const {
  // @@protoc_insertion_point(field_get:MessageResponsePlayerProfile.playerAvatar)
  return playeravatar_.GetNoArena(_default_playeravatar_);
}
 void MessageResponsePlayerProfile::set_playeravatar(const ::std::string& value) {
  set_has_playeravatar();
  playeravatar_.SetNoArena(_default_playeravatar_, value);
  // @@protoc_insertion_point(field_set:MessageResponsePlayerProfile.playerAvatar)
}
 void MessageResponsePlayerProfile::set_playeravatar(const char* value) {
  set_has_playeravatar();
  playeravatar_.SetNoArena(_default_playeravatar_, ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageResponsePlayerProfile.playerAvatar)
}
 void MessageResponsePlayerProfile::set_playeravatar(const void* value, size_t size) {
  set_has_playeravatar();
  playeravatar_.SetNoArena(_default_playeravatar_,
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageResponsePlayerProfile.playerAvatar)
}
 ::std::string* MessageResponsePlayerProfile::mutable_playeravatar() {
  set_has_playeravatar();
  // @@protoc_insertion_point(field_mutable:MessageResponsePlayerProfile.playerAvatar)
  return playeravatar_.MutableNoArena(_default_playeravatar_);
}
 ::std::string* MessageResponsePlayerProfile::release_playeravatar() {
  // @@protoc_insertion_point(field_release:MessageResponsePlayerProfile.playerAvatar)
  clear_has_playeravatar();
  return playeravatar_.ReleaseNoArena(_default_playeravatar_);
}
 void MessageResponsePlayerProfile::set_allocated_playeravatar(::std::string* playeravatar) {
  if (playeravatar != NULL) {
    set_has_playeravatar();
  } else {
    clear_has_playeravatar();
  }
  playeravatar_.SetAllocatedNoArena(_default_playeravatar_, playeravatar);
  // @@protoc_insertion_point(field_set_allocated:MessageResponsePlayerProfile.playerAvatar)
}

// required int32 playerWins = 5 [default = 0];
bool MessageResponsePlayerProfile::has_playerwins() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void MessageResponsePlayerProfile::set_has_playerwins() {
  _has_bits_[0] |= 0x00000010u;
}
void MessageResponsePlayerProfile::clear_has_playerwins() {
  _has_bits_[0] &= ~0x00000010u;
}
void MessageResponsePlayerProfile::clear_playerwins() {
  playerwins_ = 0;
  clear_has_playerwins();
}
 ::google::protobuf::int32 MessageResponsePlayerProfile::playerwins() const {
  // @@protoc_insertion_point(field_get:MessageResponsePlayerProfile.playerWins)
  return playerwins_;
}
 void MessageResponsePlayerProfile::set_playerwins(::google::protobuf::int32 value) {
  set_has_playerwins();
  playerwins_ = value;
  // @@protoc_insertion_point(field_set:MessageResponsePlayerProfile.playerWins)
}

// required int32 playerLoses = 6 [default = 0];
bool MessageResponsePlayerProfile::has_playerloses() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void MessageResponsePlayerProfile::set_has_playerloses() {
  _has_bits_[0] |= 0x00000020u;
}
void MessageResponsePlayerProfile::clear_has_playerloses() {
  _has_bits_[0] &= ~0x00000020u;
}
void MessageResponsePlayerProfile::clear_playerloses() {
  playerloses_ = 0;
  clear_has_playerloses();
}
 ::google::protobuf::int32 MessageResponsePlayerProfile::playerloses() const {
  // @@protoc_insertion_point(field_get:MessageResponsePlayerProfile.playerLoses)
  return playerloses_;
}
 void MessageResponsePlayerProfile::set_playerloses(::google::protobuf::int32 value) {
  set_has_playerloses();
  playerloses_ = value;
  // @@protoc_insertion_point(field_set:MessageResponsePlayerProfile.playerLoses)
}

// required int32 playerRating = 7 [default = 0];
bool MessageResponsePlayerProfile::has_playerrating() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void MessageResponsePlayerProfile::set_has_playerrating() {
  _has_bits_[0] |= 0x00000040u;
}
void MessageResponsePlayerProfile::clear_has_playerrating() {
  _has_bits_[0] &= ~0x00000040u;
}
void MessageResponsePlayerProfile::clear_playerrating() {
  playerrating_ = 0;
  clear_has_playerrating();
}
 ::google::protobuf::int32 MessageResponsePlayerProfile::playerrating() const {
  // @@protoc_insertion_point(field_get:MessageResponsePlayerProfile.playerRating)
  return playerrating_;
}
 void MessageResponsePlayerProfile::set_playerrating(::google::protobuf::int32 value) {
  set_has_playerrating();
  playerrating_ = value;
  // @@protoc_insertion_point(field_set:MessageResponsePlayerProfile.playerRating)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
