// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseSetPlayerTypeAndPosition.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageResponseSetPlayerTypeAndPosition.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageResponseSetPlayerTypeAndPosition_2eproto() {
  delete MessageResponseSetPlayerTypeAndPosition::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::protobuf_AddDesc_MessageResponseRoomPlayerInfo_2eproto();
  MessageResponseSetPlayerTypeAndPosition::default_instance_ = new MessageResponseSetPlayerTypeAndPosition();
  MessageResponseSetPlayerTypeAndPosition::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageResponseSetPlayerTypeAndPosition_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto_once_);
void protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto_once_,
                 &protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageResponseSetPlayerTypeAndPosition_2eproto {
  StaticDescriptorInitializer_MessageResponseSetPlayerTypeAndPosition_2eproto() {
    protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto();
  }
} static_descriptor_initializer_MessageResponseSetPlayerTypeAndPosition_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageResponseSetPlayerTypeAndPosition(
    MessageResponseSetPlayerTypeAndPosition* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageResponseSetPlayerTypeAndPosition::kRoomIdFieldNumber;
const int MessageResponseSetPlayerTypeAndPosition::kPlayerFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageResponseSetPlayerTypeAndPosition::MessageResponseSetPlayerTypeAndPosition()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageResponseSetPlayerTypeAndPosition)
}

void MessageResponseSetPlayerTypeAndPosition::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  player_ = const_cast< ::MessageResponseRoomPlayerInfo*>(
      ::MessageResponseRoomPlayerInfo::internal_default_instance());
#else
  player_ = const_cast< ::MessageResponseRoomPlayerInfo*>(&::MessageResponseRoomPlayerInfo::default_instance());
#endif
}

MessageResponseSetPlayerTypeAndPosition::MessageResponseSetPlayerTypeAndPosition(const MessageResponseSetPlayerTypeAndPosition& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageResponseSetPlayerTypeAndPosition)
}

void MessageResponseSetPlayerTypeAndPosition::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  roomid_ = GOOGLE_LONGLONG(0);
  player_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageResponseSetPlayerTypeAndPosition::~MessageResponseSetPlayerTypeAndPosition() {
  // @@protoc_insertion_point(destructor:MessageResponseSetPlayerTypeAndPosition)
  SharedDtor();
}

void MessageResponseSetPlayerTypeAndPosition::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete player_;
  }
}

void MessageResponseSetPlayerTypeAndPosition::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageResponseSetPlayerTypeAndPosition& MessageResponseSetPlayerTypeAndPosition::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageResponseSetPlayerTypeAndPosition_2eproto();
#endif
  return *default_instance_;
}

MessageResponseSetPlayerTypeAndPosition* MessageResponseSetPlayerTypeAndPosition::default_instance_ = NULL;

MessageResponseSetPlayerTypeAndPosition* MessageResponseSetPlayerTypeAndPosition::New(::google::protobuf::Arena* arena) const {
  MessageResponseSetPlayerTypeAndPosition* n = new MessageResponseSetPlayerTypeAndPosition;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageResponseSetPlayerTypeAndPosition::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageResponseSetPlayerTypeAndPosition)
  if (_has_bits_[0 / 32] & 3u) {
    roomid_ = GOOGLE_LONGLONG(0);
    if (has_player()) {
      if (player_ != NULL) player_->::MessageResponseRoomPlayerInfo::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageResponseSetPlayerTypeAndPosition::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageResponseSetPlayerTypeAndPosition, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageResponseSetPlayerTypeAndPosition)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 roomId = 1 [default = 0];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &roomid_)));
          set_has_roomid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_player;
        break;
      }

      // required .MessageResponseRoomPlayerInfo player = 2;
      case 2: {
        if (tag == 18) {
         parse_player:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_player()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageResponseSetPlayerTypeAndPosition)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageResponseSetPlayerTypeAndPosition)
  return false;
#undef DO_
}

void MessageResponseSetPlayerTypeAndPosition::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageResponseSetPlayerTypeAndPosition)
  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->roomid(), output);
  }

  // required .MessageResponseRoomPlayerInfo player = 2;
  if (has_player()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->player_, output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageResponseSetPlayerTypeAndPosition)
}

int MessageResponseSetPlayerTypeAndPosition::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MessageResponseSetPlayerTypeAndPosition)
  int total_size = 0;

  if (has_roomid()) {
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());
  }

  if (has_player()) {
    // required .MessageResponseRoomPlayerInfo player = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->player_);
  }

  return total_size;
}
int MessageResponseSetPlayerTypeAndPosition::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageResponseSetPlayerTypeAndPosition)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());

    // required .MessageResponseRoomPlayerInfo player = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->player_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageResponseSetPlayerTypeAndPosition::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageResponseSetPlayerTypeAndPosition*>(&from));
}

void MessageResponseSetPlayerTypeAndPosition::MergeFrom(const MessageResponseSetPlayerTypeAndPosition& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageResponseSetPlayerTypeAndPosition)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_roomid()) {
      set_roomid(from.roomid());
    }
    if (from.has_player()) {
      mutable_player()->::MessageResponseRoomPlayerInfo::MergeFrom(from.player());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageResponseSetPlayerTypeAndPosition::CopyFrom(const MessageResponseSetPlayerTypeAndPosition& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageResponseSetPlayerTypeAndPosition)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageResponseSetPlayerTypeAndPosition::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_player()) {
    if (!this->player_->IsInitialized()) return false;
  }
  return true;
}

void MessageResponseSetPlayerTypeAndPosition::Swap(MessageResponseSetPlayerTypeAndPosition* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageResponseSetPlayerTypeAndPosition::InternalSwap(MessageResponseSetPlayerTypeAndPosition* other) {
  std::swap(roomid_, other->roomid_);
  std::swap(player_, other->player_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageResponseSetPlayerTypeAndPosition::GetTypeName() const {
  return "MessageResponseSetPlayerTypeAndPosition";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseSetPlayerTypeAndPosition

// required int64 roomId = 1 [default = 0];
bool MessageResponseSetPlayerTypeAndPosition::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageResponseSetPlayerTypeAndPosition::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageResponseSetPlayerTypeAndPosition::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageResponseSetPlayerTypeAndPosition::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
 ::google::protobuf::int64 MessageResponseSetPlayerTypeAndPosition::roomid() const {
  // @@protoc_insertion_point(field_get:MessageResponseSetPlayerTypeAndPosition.roomId)
  return roomid_;
}
 void MessageResponseSetPlayerTypeAndPosition::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseSetPlayerTypeAndPosition.roomId)
}

// required .MessageResponseRoomPlayerInfo player = 2;
bool MessageResponseSetPlayerTypeAndPosition::has_player() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MessageResponseSetPlayerTypeAndPosition::set_has_player() {
  _has_bits_[0] |= 0x00000002u;
}
void MessageResponseSetPlayerTypeAndPosition::clear_has_player() {
  _has_bits_[0] &= ~0x00000002u;
}
void MessageResponseSetPlayerTypeAndPosition::clear_player() {
  if (player_ != NULL) player_->::MessageResponseRoomPlayerInfo::Clear();
  clear_has_player();
}
const ::MessageResponseRoomPlayerInfo& MessageResponseSetPlayerTypeAndPosition::player() const {
  // @@protoc_insertion_point(field_get:MessageResponseSetPlayerTypeAndPosition.player)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return player_ != NULL ? *player_ : *default_instance().player_;
#else
  return player_ != NULL ? *player_ : *default_instance_->player_;
#endif
}
::MessageResponseRoomPlayerInfo* MessageResponseSetPlayerTypeAndPosition::mutable_player() {
  set_has_player();
  if (player_ == NULL) {
    player_ = new ::MessageResponseRoomPlayerInfo;
  }
  // @@protoc_insertion_point(field_mutable:MessageResponseSetPlayerTypeAndPosition.player)
  return player_;
}
::MessageResponseRoomPlayerInfo* MessageResponseSetPlayerTypeAndPosition::release_player() {
  // @@protoc_insertion_point(field_release:MessageResponseSetPlayerTypeAndPosition.player)
  clear_has_player();
  ::MessageResponseRoomPlayerInfo* temp = player_;
  player_ = NULL;
  return temp;
}
void MessageResponseSetPlayerTypeAndPosition::set_allocated_player(::MessageResponseRoomPlayerInfo* player) {
  delete player_;
  player_ = player;
  if (player) {
    set_has_player();
  } else {
    clear_has_player();
  }
  // @@protoc_insertion_point(field_set_allocated:MessageResponseSetPlayerTypeAndPosition.player)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
