// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseShopItemList.proto

#ifndef PROTOBUF_MessageResponseShopItemList_2eproto__INCLUDED
#define PROTOBUF_MessageResponseShopItemList_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "MessageResponseShopItem.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MessageResponseShopItemList_2eproto();
void protobuf_AssignDesc_MessageResponseShopItemList_2eproto();
void protobuf_ShutdownFile_MessageResponseShopItemList_2eproto();

class MessageResponseShopItemList;

// ===================================================================

class MessageResponseShopItemList : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:MessageResponseShopItemList) */ {
 public:
  MessageResponseShopItemList();
  virtual ~MessageResponseShopItemList();

  MessageResponseShopItemList(const MessageResponseShopItemList& from);

  inline MessageResponseShopItemList& operator=(const MessageResponseShopItemList& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const MessageResponseShopItemList& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MessageResponseShopItemList* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MessageResponseShopItemList* other);

  // implements Message ----------------------------------------------

  inline MessageResponseShopItemList* New() const { return New(NULL); }

  MessageResponseShopItemList* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MessageResponseShopItemList& from);
  void MergeFrom(const MessageResponseShopItemList& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageResponseShopItemList* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .MessageResponseShopItem shopItemList = 1;
  int shopitemlist_size() const;
  void clear_shopitemlist();
  static const int kShopItemListFieldNumber = 1;
  const ::MessageResponseShopItem& shopitemlist(int index) const;
  ::MessageResponseShopItem* mutable_shopitemlist(int index);
  ::MessageResponseShopItem* add_shopitemlist();
  ::google::protobuf::RepeatedPtrField< ::MessageResponseShopItem >*
      mutable_shopitemlist();
  const ::google::protobuf::RepeatedPtrField< ::MessageResponseShopItem >&
      shopitemlist() const;

  // @@protoc_insertion_point(class_scope:MessageResponseShopItemList)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::MessageResponseShopItem > shopitemlist_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MessageResponseShopItemList_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MessageResponseShopItemList_2eproto();
  #endif
  friend void protobuf_AssignDesc_MessageResponseShopItemList_2eproto();
  friend void protobuf_ShutdownFile_MessageResponseShopItemList_2eproto();

  void InitAsDefaultInstance();
  static MessageResponseShopItemList* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseShopItemList

// repeated .MessageResponseShopItem shopItemList = 1;
inline int MessageResponseShopItemList::shopitemlist_size() const {
  return shopitemlist_.size();
}
inline void MessageResponseShopItemList::clear_shopitemlist() {
  shopitemlist_.Clear();
}
inline const ::MessageResponseShopItem& MessageResponseShopItemList::shopitemlist(int index) const {
  // @@protoc_insertion_point(field_get:MessageResponseShopItemList.shopItemList)
  return shopitemlist_.Get(index);
}
inline ::MessageResponseShopItem* MessageResponseShopItemList::mutable_shopitemlist(int index) {
  // @@protoc_insertion_point(field_mutable:MessageResponseShopItemList.shopItemList)
  return shopitemlist_.Mutable(index);
}
inline ::MessageResponseShopItem* MessageResponseShopItemList::add_shopitemlist() {
  // @@protoc_insertion_point(field_add:MessageResponseShopItemList.shopItemList)
  return shopitemlist_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::MessageResponseShopItem >*
MessageResponseShopItemList::mutable_shopitemlist() {
  // @@protoc_insertion_point(field_mutable_list:MessageResponseShopItemList.shopItemList)
  return &shopitemlist_;
}
inline const ::google::protobuf::RepeatedPtrField< ::MessageResponseShopItem >&
MessageResponseShopItemList::shopitemlist() const {
  // @@protoc_insertion_point(field_list:MessageResponseShopItemList.shopItemList)
  return shopitemlist_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageResponseShopItemList_2eproto__INCLUDED
