// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRequestBuyShopItem.proto

#ifndef PROTOBUF_MessageRequestBuyShopItem_2eproto__INCLUDED
#define PROTOBUF_MessageRequestBuyShopItem_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MessageRequestBuyShopItem_2eproto();
void protobuf_AssignDesc_MessageRequestBuyShopItem_2eproto();
void protobuf_ShutdownFile_MessageRequestBuyShopItem_2eproto();

class MessageRequestBuyShopItem;

enum MessageRequestBuyShopItem_eMarketType {
  MessageRequestBuyShopItem_eMarketType_atNone = 0,
  MessageRequestBuyShopItem_eMarketType_atApple = 1,
  MessageRequestBuyShopItem_eMarketType_atGoogle = 2
};
bool MessageRequestBuyShopItem_eMarketType_IsValid(int value);
const MessageRequestBuyShopItem_eMarketType MessageRequestBuyShopItem_eMarketType_eMarketType_MIN = MessageRequestBuyShopItem_eMarketType_atNone;
const MessageRequestBuyShopItem_eMarketType MessageRequestBuyShopItem_eMarketType_eMarketType_MAX = MessageRequestBuyShopItem_eMarketType_atGoogle;
const int MessageRequestBuyShopItem_eMarketType_eMarketType_ARRAYSIZE = MessageRequestBuyShopItem_eMarketType_eMarketType_MAX + 1;

enum MessageRequestBuyShopItem_eBuyType {
  MessageRequestBuyShopItem_eBuyType_btRealMoney = 0,
  MessageRequestBuyShopItem_eBuyType_btInGameCash = 1
};
bool MessageRequestBuyShopItem_eBuyType_IsValid(int value);
const MessageRequestBuyShopItem_eBuyType MessageRequestBuyShopItem_eBuyType_eBuyType_MIN = MessageRequestBuyShopItem_eBuyType_btRealMoney;
const MessageRequestBuyShopItem_eBuyType MessageRequestBuyShopItem_eBuyType_eBuyType_MAX = MessageRequestBuyShopItem_eBuyType_btInGameCash;
const int MessageRequestBuyShopItem_eBuyType_eBuyType_ARRAYSIZE = MessageRequestBuyShopItem_eBuyType_eBuyType_MAX + 1;

enum MessageRequestBuyShopItem_eItemType {
  MessageRequestBuyShopItem_eItemType_itItem = 0,
  MessageRequestBuyShopItem_eItemType_itItemCollection = 1
};
bool MessageRequestBuyShopItem_eItemType_IsValid(int value);
const MessageRequestBuyShopItem_eItemType MessageRequestBuyShopItem_eItemType_eItemType_MIN = MessageRequestBuyShopItem_eItemType_itItem;
const MessageRequestBuyShopItem_eItemType MessageRequestBuyShopItem_eItemType_eItemType_MAX = MessageRequestBuyShopItem_eItemType_itItemCollection;
const int MessageRequestBuyShopItem_eItemType_eItemType_ARRAYSIZE = MessageRequestBuyShopItem_eItemType_eItemType_MAX + 1;

// ===================================================================

class MessageRequestBuyShopItem : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:MessageRequestBuyShopItem) */ {
 public:
  MessageRequestBuyShopItem();
  virtual ~MessageRequestBuyShopItem();

  MessageRequestBuyShopItem(const MessageRequestBuyShopItem& from);

  inline MessageRequestBuyShopItem& operator=(const MessageRequestBuyShopItem& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const MessageRequestBuyShopItem& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MessageRequestBuyShopItem* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MessageRequestBuyShopItem* other);

  // implements Message ----------------------------------------------

  inline MessageRequestBuyShopItem* New() const { return New(NULL); }

  MessageRequestBuyShopItem* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MessageRequestBuyShopItem& from);
  void MergeFrom(const MessageRequestBuyShopItem& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageRequestBuyShopItem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  typedef MessageRequestBuyShopItem_eMarketType eMarketType;
  static const eMarketType atNone =
    MessageRequestBuyShopItem_eMarketType_atNone;
  static const eMarketType atApple =
    MessageRequestBuyShopItem_eMarketType_atApple;
  static const eMarketType atGoogle =
    MessageRequestBuyShopItem_eMarketType_atGoogle;
  static inline bool eMarketType_IsValid(int value) {
    return MessageRequestBuyShopItem_eMarketType_IsValid(value);
  }
  static const eMarketType eMarketType_MIN =
    MessageRequestBuyShopItem_eMarketType_eMarketType_MIN;
  static const eMarketType eMarketType_MAX =
    MessageRequestBuyShopItem_eMarketType_eMarketType_MAX;
  static const int eMarketType_ARRAYSIZE =
    MessageRequestBuyShopItem_eMarketType_eMarketType_ARRAYSIZE;

  typedef MessageRequestBuyShopItem_eBuyType eBuyType;
  static const eBuyType btRealMoney =
    MessageRequestBuyShopItem_eBuyType_btRealMoney;
  static const eBuyType btInGameCash =
    MessageRequestBuyShopItem_eBuyType_btInGameCash;
  static inline bool eBuyType_IsValid(int value) {
    return MessageRequestBuyShopItem_eBuyType_IsValid(value);
  }
  static const eBuyType eBuyType_MIN =
    MessageRequestBuyShopItem_eBuyType_eBuyType_MIN;
  static const eBuyType eBuyType_MAX =
    MessageRequestBuyShopItem_eBuyType_eBuyType_MAX;
  static const int eBuyType_ARRAYSIZE =
    MessageRequestBuyShopItem_eBuyType_eBuyType_ARRAYSIZE;

  typedef MessageRequestBuyShopItem_eItemType eItemType;
  static const eItemType itItem =
    MessageRequestBuyShopItem_eItemType_itItem;
  static const eItemType itItemCollection =
    MessageRequestBuyShopItem_eItemType_itItemCollection;
  static inline bool eItemType_IsValid(int value) {
    return MessageRequestBuyShopItem_eItemType_IsValid(value);
  }
  static const eItemType eItemType_MIN =
    MessageRequestBuyShopItem_eItemType_eItemType_MIN;
  static const eItemType eItemType_MAX =
    MessageRequestBuyShopItem_eItemType_eItemType_MAX;
  static const int eItemType_ARRAYSIZE =
    MessageRequestBuyShopItem_eItemType_eItemType_ARRAYSIZE;

  // accessors -------------------------------------------------------

  // required .MessageRequestBuyShopItem.eMarketType marketType = 1 [default = atNone];
  bool has_markettype() const;
  void clear_markettype();
  static const int kMarketTypeFieldNumber = 1;
  ::MessageRequestBuyShopItem_eMarketType markettype() const;
  void set_markettype(::MessageRequestBuyShopItem_eMarketType value);

  // required string shopItemName = 2 [default = ""];
  bool has_shopitemname() const;
  void clear_shopitemname();
  static const int kShopItemNameFieldNumber = 2;
  const ::std::string& shopitemname() const;
  void set_shopitemname(const ::std::string& value);
  void set_shopitemname(const char* value);
  void set_shopitemname(const char* value, size_t size);
  ::std::string* mutable_shopitemname();
  ::std::string* release_shopitemname();
  void set_allocated_shopitemname(::std::string* shopitemname);

  // required bytes receipt = 3 [default = "\000"];
  bool has_receipt() const;
  void clear_receipt();
  static const int kReceiptFieldNumber = 3;
  const ::std::string& receipt() const;
  void set_receipt(const ::std::string& value);
  void set_receipt(const char* value);
  void set_receipt(const void* value, size_t size);
  ::std::string* mutable_receipt();
  ::std::string* release_receipt();
  void set_allocated_receipt(::std::string* receipt);

  // required .MessageRequestBuyShopItem.eBuyType buyType = 4 [default = btInGameCash];
  bool has_buytype() const;
  void clear_buytype();
  static const int kBuyTypeFieldNumber = 4;
  ::MessageRequestBuyShopItem_eBuyType buytype() const;
  void set_buytype(::MessageRequestBuyShopItem_eBuyType value);

  // required .MessageRequestBuyShopItem.eItemType itemType = 5 [default = itItem];
  bool has_itemtype() const;
  void clear_itemtype();
  static const int kItemTypeFieldNumber = 5;
  ::MessageRequestBuyShopItem_eItemType itemtype() const;
  void set_itemtype(::MessageRequestBuyShopItem_eItemType value);

  // @@protoc_insertion_point(class_scope:MessageRequestBuyShopItem)
 private:
  inline void set_has_markettype();
  inline void clear_has_markettype();
  inline void set_has_shopitemname();
  inline void clear_has_shopitemname();
  inline void set_has_receipt();
  inline void clear_has_receipt();
  inline void set_has_buytype();
  inline void clear_has_buytype();
  inline void set_has_itemtype();
  inline void clear_has_itemtype();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr shopitemname_;
  int markettype_;
  int buytype_;
  static ::std::string* _default_receipt_;
  ::google::protobuf::internal::ArenaStringPtr receipt_;
  int itemtype_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MessageRequestBuyShopItem_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MessageRequestBuyShopItem_2eproto();
  #endif
  friend void protobuf_AssignDesc_MessageRequestBuyShopItem_2eproto();
  friend void protobuf_ShutdownFile_MessageRequestBuyShopItem_2eproto();

  void InitAsDefaultInstance();
  static MessageRequestBuyShopItem* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageRequestBuyShopItem

// required .MessageRequestBuyShopItem.eMarketType marketType = 1 [default = atNone];
inline bool MessageRequestBuyShopItem::has_markettype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageRequestBuyShopItem::set_has_markettype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageRequestBuyShopItem::clear_has_markettype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageRequestBuyShopItem::clear_markettype() {
  markettype_ = 0;
  clear_has_markettype();
}
inline ::MessageRequestBuyShopItem_eMarketType MessageRequestBuyShopItem::markettype() const {
  // @@protoc_insertion_point(field_get:MessageRequestBuyShopItem.marketType)
  return static_cast< ::MessageRequestBuyShopItem_eMarketType >(markettype_);
}
inline void MessageRequestBuyShopItem::set_markettype(::MessageRequestBuyShopItem_eMarketType value) {
  assert(::MessageRequestBuyShopItem_eMarketType_IsValid(value));
  set_has_markettype();
  markettype_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestBuyShopItem.marketType)
}

// required string shopItemName = 2 [default = ""];
inline bool MessageRequestBuyShopItem::has_shopitemname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageRequestBuyShopItem::set_has_shopitemname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageRequestBuyShopItem::clear_has_shopitemname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageRequestBuyShopItem::clear_shopitemname() {
  shopitemname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_shopitemname();
}
inline const ::std::string& MessageRequestBuyShopItem::shopitemname() const {
  // @@protoc_insertion_point(field_get:MessageRequestBuyShopItem.shopItemName)
  return shopitemname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageRequestBuyShopItem::set_shopitemname(const ::std::string& value) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageRequestBuyShopItem.shopItemName)
}
inline void MessageRequestBuyShopItem::set_shopitemname(const char* value) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageRequestBuyShopItem.shopItemName)
}
inline void MessageRequestBuyShopItem::set_shopitemname(const char* value, size_t size) {
  set_has_shopitemname();
  shopitemname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageRequestBuyShopItem.shopItemName)
}
inline ::std::string* MessageRequestBuyShopItem::mutable_shopitemname() {
  set_has_shopitemname();
  // @@protoc_insertion_point(field_mutable:MessageRequestBuyShopItem.shopItemName)
  return shopitemname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MessageRequestBuyShopItem::release_shopitemname() {
  // @@protoc_insertion_point(field_release:MessageRequestBuyShopItem.shopItemName)
  clear_has_shopitemname();
  return shopitemname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MessageRequestBuyShopItem::set_allocated_shopitemname(::std::string* shopitemname) {
  if (shopitemname != NULL) {
    set_has_shopitemname();
  } else {
    clear_has_shopitemname();
  }
  shopitemname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), shopitemname);
  // @@protoc_insertion_point(field_set_allocated:MessageRequestBuyShopItem.shopItemName)
}

// required bytes receipt = 3 [default = "\000"];
inline bool MessageRequestBuyShopItem::has_receipt() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageRequestBuyShopItem::set_has_receipt() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageRequestBuyShopItem::clear_has_receipt() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageRequestBuyShopItem::clear_receipt() {
  receipt_.ClearToDefaultNoArena(_default_receipt_);
  clear_has_receipt();
}
inline const ::std::string& MessageRequestBuyShopItem::receipt() const {
  // @@protoc_insertion_point(field_get:MessageRequestBuyShopItem.receipt)
  return receipt_.GetNoArena(_default_receipt_);
}
inline void MessageRequestBuyShopItem::set_receipt(const ::std::string& value) {
  set_has_receipt();
  receipt_.SetNoArena(_default_receipt_, value);
  // @@protoc_insertion_point(field_set:MessageRequestBuyShopItem.receipt)
}
inline void MessageRequestBuyShopItem::set_receipt(const char* value) {
  set_has_receipt();
  receipt_.SetNoArena(_default_receipt_, ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageRequestBuyShopItem.receipt)
}
inline void MessageRequestBuyShopItem::set_receipt(const void* value, size_t size) {
  set_has_receipt();
  receipt_.SetNoArena(_default_receipt_,
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageRequestBuyShopItem.receipt)
}
inline ::std::string* MessageRequestBuyShopItem::mutable_receipt() {
  set_has_receipt();
  // @@protoc_insertion_point(field_mutable:MessageRequestBuyShopItem.receipt)
  return receipt_.MutableNoArena(_default_receipt_);
}
inline ::std::string* MessageRequestBuyShopItem::release_receipt() {
  // @@protoc_insertion_point(field_release:MessageRequestBuyShopItem.receipt)
  clear_has_receipt();
  return receipt_.ReleaseNoArena(_default_receipt_);
}
inline void MessageRequestBuyShopItem::set_allocated_receipt(::std::string* receipt) {
  if (receipt != NULL) {
    set_has_receipt();
  } else {
    clear_has_receipt();
  }
  receipt_.SetAllocatedNoArena(_default_receipt_, receipt);
  // @@protoc_insertion_point(field_set_allocated:MessageRequestBuyShopItem.receipt)
}

// required .MessageRequestBuyShopItem.eBuyType buyType = 4 [default = btInGameCash];
inline bool MessageRequestBuyShopItem::has_buytype() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageRequestBuyShopItem::set_has_buytype() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageRequestBuyShopItem::clear_has_buytype() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageRequestBuyShopItem::clear_buytype() {
  buytype_ = 1;
  clear_has_buytype();
}
inline ::MessageRequestBuyShopItem_eBuyType MessageRequestBuyShopItem::buytype() const {
  // @@protoc_insertion_point(field_get:MessageRequestBuyShopItem.buyType)
  return static_cast< ::MessageRequestBuyShopItem_eBuyType >(buytype_);
}
inline void MessageRequestBuyShopItem::set_buytype(::MessageRequestBuyShopItem_eBuyType value) {
  assert(::MessageRequestBuyShopItem_eBuyType_IsValid(value));
  set_has_buytype();
  buytype_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestBuyShopItem.buyType)
}

// required .MessageRequestBuyShopItem.eItemType itemType = 5 [default = itItem];
inline bool MessageRequestBuyShopItem::has_itemtype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessageRequestBuyShopItem::set_has_itemtype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessageRequestBuyShopItem::clear_has_itemtype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessageRequestBuyShopItem::clear_itemtype() {
  itemtype_ = 0;
  clear_has_itemtype();
}
inline ::MessageRequestBuyShopItem_eItemType MessageRequestBuyShopItem::itemtype() const {
  // @@protoc_insertion_point(field_get:MessageRequestBuyShopItem.itemType)
  return static_cast< ::MessageRequestBuyShopItem_eItemType >(itemtype_);
}
inline void MessageRequestBuyShopItem::set_itemtype(::MessageRequestBuyShopItem_eItemType value) {
  assert(::MessageRequestBuyShopItem_eItemType_IsValid(value));
  set_has_itemtype();
  itemtype_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestBuyShopItem.itemType)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MessageRequestBuyShopItem_eMarketType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::MessageRequestBuyShopItem_eBuyType> : ::google::protobuf::internal::true_type {};
template <> struct is_proto_enum< ::MessageRequestBuyShopItem_eItemType> : ::google::protobuf::internal::true_type {};

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageRequestBuyShopItem_2eproto__INCLUDED
