// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRequestSetPlayerBullets.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageRequestSetPlayerBullets.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageRequestSetPlayerBullets_2eproto() {
  delete MessageRequestSetPlayerBullets::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  MessageRequestSetPlayerBullets::default_instance_ = new MessageRequestSetPlayerBullets();
  MessageRequestSetPlayerBullets::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageRequestSetPlayerBullets_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto_once_);
void protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto_once_,
                 &protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageRequestSetPlayerBullets_2eproto {
  StaticDescriptorInitializer_MessageRequestSetPlayerBullets_2eproto() {
    protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto();
  }
} static_descriptor_initializer_MessageRequestSetPlayerBullets_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageRequestSetPlayerBullets(
    MessageRequestSetPlayerBullets* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageRequestSetPlayerBullets::kRoomIdFieldNumber;
const int MessageRequestSetPlayerBullets::kB1FieldNumber;
const int MessageRequestSetPlayerBullets::kB2FieldNumber;
const int MessageRequestSetPlayerBullets::kB3FieldNumber;
const int MessageRequestSetPlayerBullets::kB4FieldNumber;
const int MessageRequestSetPlayerBullets::kB5FieldNumber;
const int MessageRequestSetPlayerBullets::kB6FieldNumber;
const int MessageRequestSetPlayerBullets::kB7FieldNumber;
const int MessageRequestSetPlayerBullets::kB8FieldNumber;
const int MessageRequestSetPlayerBullets::kB9FieldNumber;
const int MessageRequestSetPlayerBullets::kB10FieldNumber;
const int MessageRequestSetPlayerBullets::kB11FieldNumber;
const int MessageRequestSetPlayerBullets::kB12FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageRequestSetPlayerBullets::MessageRequestSetPlayerBullets()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageRequestSetPlayerBullets)
}

void MessageRequestSetPlayerBullets::InitAsDefaultInstance() {
}

MessageRequestSetPlayerBullets::MessageRequestSetPlayerBullets(const MessageRequestSetPlayerBullets& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageRequestSetPlayerBullets)
}

void MessageRequestSetPlayerBullets::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  roomid_ = GOOGLE_LONGLONG(0);
  b1_ = false;
  b2_ = false;
  b3_ = false;
  b4_ = false;
  b5_ = false;
  b6_ = false;
  b7_ = false;
  b8_ = false;
  b9_ = false;
  b10_ = false;
  b11_ = false;
  b12_ = false;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageRequestSetPlayerBullets::~MessageRequestSetPlayerBullets() {
  // @@protoc_insertion_point(destructor:MessageRequestSetPlayerBullets)
  SharedDtor();
}

void MessageRequestSetPlayerBullets::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MessageRequestSetPlayerBullets::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageRequestSetPlayerBullets& MessageRequestSetPlayerBullets::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageRequestSetPlayerBullets_2eproto();
#endif
  return *default_instance_;
}

MessageRequestSetPlayerBullets* MessageRequestSetPlayerBullets::default_instance_ = NULL;

MessageRequestSetPlayerBullets* MessageRequestSetPlayerBullets::New(::google::protobuf::Arena* arena) const {
  MessageRequestSetPlayerBullets* n = new MessageRequestSetPlayerBullets;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageRequestSetPlayerBullets::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageRequestSetPlayerBullets)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(MessageRequestSetPlayerBullets, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<MessageRequestSetPlayerBullets*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  if (_has_bits_[0 / 32] & 255u) {
    ZR_(roomid_, b7_);
  }
  if (_has_bits_[8 / 32] & 7936u) {
    ZR_(b8_, b12_);
  }

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageRequestSetPlayerBullets::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageRequestSetPlayerBullets, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageRequestSetPlayerBullets)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 roomId = 1 [default = 0];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &roomid_)));
          set_has_roomid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_b1;
        break;
      }

      // required bool b1 = 2 [default = false];
      case 2: {
        if (tag == 16) {
         parse_b1:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b1_)));
          set_has_b1();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_b2;
        break;
      }

      // required bool b2 = 3 [default = false];
      case 3: {
        if (tag == 24) {
         parse_b2:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b2_)));
          set_has_b2();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_b3;
        break;
      }

      // required bool b3 = 4 [default = false];
      case 4: {
        if (tag == 32) {
         parse_b3:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b3_)));
          set_has_b3();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_b4;
        break;
      }

      // required bool b4 = 5 [default = false];
      case 5: {
        if (tag == 40) {
         parse_b4:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b4_)));
          set_has_b4();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_b5;
        break;
      }

      // required bool b5 = 6 [default = false];
      case 6: {
        if (tag == 48) {
         parse_b5:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b5_)));
          set_has_b5();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_b6;
        break;
      }

      // required bool b6 = 7 [default = false];
      case 7: {
        if (tag == 56) {
         parse_b6:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b6_)));
          set_has_b6();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(64)) goto parse_b7;
        break;
      }

      // required bool b7 = 8 [default = false];
      case 8: {
        if (tag == 64) {
         parse_b7:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b7_)));
          set_has_b7();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(72)) goto parse_b8;
        break;
      }

      // required bool b8 = 9 [default = false];
      case 9: {
        if (tag == 72) {
         parse_b8:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b8_)));
          set_has_b8();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_b9;
        break;
      }

      // required bool b9 = 10 [default = false];
      case 10: {
        if (tag == 80) {
         parse_b9:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b9_)));
          set_has_b9();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(88)) goto parse_b10;
        break;
      }

      // required bool b10 = 11 [default = false];
      case 11: {
        if (tag == 88) {
         parse_b10:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b10_)));
          set_has_b10();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(96)) goto parse_b11;
        break;
      }

      // required bool b11 = 12 [default = false];
      case 12: {
        if (tag == 96) {
         parse_b11:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b11_)));
          set_has_b11();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(104)) goto parse_b12;
        break;
      }

      // required bool b12 = 13 [default = false];
      case 13: {
        if (tag == 104) {
         parse_b12:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &b12_)));
          set_has_b12();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageRequestSetPlayerBullets)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageRequestSetPlayerBullets)
  return false;
#undef DO_
}

void MessageRequestSetPlayerBullets::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageRequestSetPlayerBullets)
  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->roomid(), output);
  }

  // required bool b1 = 2 [default = false];
  if (has_b1()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->b1(), output);
  }

  // required bool b2 = 3 [default = false];
  if (has_b2()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->b2(), output);
  }

  // required bool b3 = 4 [default = false];
  if (has_b3()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->b3(), output);
  }

  // required bool b4 = 5 [default = false];
  if (has_b4()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(5, this->b4(), output);
  }

  // required bool b5 = 6 [default = false];
  if (has_b5()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(6, this->b5(), output);
  }

  // required bool b6 = 7 [default = false];
  if (has_b6()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(7, this->b6(), output);
  }

  // required bool b7 = 8 [default = false];
  if (has_b7()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(8, this->b7(), output);
  }

  // required bool b8 = 9 [default = false];
  if (has_b8()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(9, this->b8(), output);
  }

  // required bool b9 = 10 [default = false];
  if (has_b9()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->b9(), output);
  }

  // required bool b10 = 11 [default = false];
  if (has_b10()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->b10(), output);
  }

  // required bool b11 = 12 [default = false];
  if (has_b11()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->b11(), output);
  }

  // required bool b12 = 13 [default = false];
  if (has_b12()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(13, this->b12(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageRequestSetPlayerBullets)
}

int MessageRequestSetPlayerBullets::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MessageRequestSetPlayerBullets)
  int total_size = 0;

  if (has_roomid()) {
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());
  }

  if (has_b1()) {
    // required bool b1 = 2 [default = false];
    total_size += 1 + 1;
  }

  if (has_b2()) {
    // required bool b2 = 3 [default = false];
    total_size += 1 + 1;
  }

  if (has_b3()) {
    // required bool b3 = 4 [default = false];
    total_size += 1 + 1;
  }

  if (has_b4()) {
    // required bool b4 = 5 [default = false];
    total_size += 1 + 1;
  }

  if (has_b5()) {
    // required bool b5 = 6 [default = false];
    total_size += 1 + 1;
  }

  if (has_b6()) {
    // required bool b6 = 7 [default = false];
    total_size += 1 + 1;
  }

  if (has_b7()) {
    // required bool b7 = 8 [default = false];
    total_size += 1 + 1;
  }

  if (has_b8()) {
    // required bool b8 = 9 [default = false];
    total_size += 1 + 1;
  }

  if (has_b9()) {
    // required bool b9 = 10 [default = false];
    total_size += 1 + 1;
  }

  if (has_b10()) {
    // required bool b10 = 11 [default = false];
    total_size += 1 + 1;
  }

  if (has_b11()) {
    // required bool b11 = 12 [default = false];
    total_size += 1 + 1;
  }

  if (has_b12()) {
    // required bool b12 = 13 [default = false];
    total_size += 1 + 1;
  }

  return total_size;
}
int MessageRequestSetPlayerBullets::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageRequestSetPlayerBullets)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00001fff) ^ 0x00001fff) == 0) {  // All required fields are present.
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());

    // required bool b1 = 2 [default = false];
    total_size += 1 + 1;

    // required bool b2 = 3 [default = false];
    total_size += 1 + 1;

    // required bool b3 = 4 [default = false];
    total_size += 1 + 1;

    // required bool b4 = 5 [default = false];
    total_size += 1 + 1;

    // required bool b5 = 6 [default = false];
    total_size += 1 + 1;

    // required bool b6 = 7 [default = false];
    total_size += 1 + 1;

    // required bool b7 = 8 [default = false];
    total_size += 1 + 1;

    // required bool b8 = 9 [default = false];
    total_size += 1 + 1;

    // required bool b9 = 10 [default = false];
    total_size += 1 + 1;

    // required bool b10 = 11 [default = false];
    total_size += 1 + 1;

    // required bool b11 = 12 [default = false];
    total_size += 1 + 1;

    // required bool b12 = 13 [default = false];
    total_size += 1 + 1;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageRequestSetPlayerBullets::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageRequestSetPlayerBullets*>(&from));
}

void MessageRequestSetPlayerBullets::MergeFrom(const MessageRequestSetPlayerBullets& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageRequestSetPlayerBullets)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_roomid()) {
      set_roomid(from.roomid());
    }
    if (from.has_b1()) {
      set_b1(from.b1());
    }
    if (from.has_b2()) {
      set_b2(from.b2());
    }
    if (from.has_b3()) {
      set_b3(from.b3());
    }
    if (from.has_b4()) {
      set_b4(from.b4());
    }
    if (from.has_b5()) {
      set_b5(from.b5());
    }
    if (from.has_b6()) {
      set_b6(from.b6());
    }
    if (from.has_b7()) {
      set_b7(from.b7());
    }
  }
  if (from._has_bits_[8 / 32] & (0xffu << (8 % 32))) {
    if (from.has_b8()) {
      set_b8(from.b8());
    }
    if (from.has_b9()) {
      set_b9(from.b9());
    }
    if (from.has_b10()) {
      set_b10(from.b10());
    }
    if (from.has_b11()) {
      set_b11(from.b11());
    }
    if (from.has_b12()) {
      set_b12(from.b12());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageRequestSetPlayerBullets::CopyFrom(const MessageRequestSetPlayerBullets& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageRequestSetPlayerBullets)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageRequestSetPlayerBullets::IsInitialized() const {
  if ((_has_bits_[0] & 0x00001fff) != 0x00001fff) return false;

  return true;
}

void MessageRequestSetPlayerBullets::Swap(MessageRequestSetPlayerBullets* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageRequestSetPlayerBullets::InternalSwap(MessageRequestSetPlayerBullets* other) {
  std::swap(roomid_, other->roomid_);
  std::swap(b1_, other->b1_);
  std::swap(b2_, other->b2_);
  std::swap(b3_, other->b3_);
  std::swap(b4_, other->b4_);
  std::swap(b5_, other->b5_);
  std::swap(b6_, other->b6_);
  std::swap(b7_, other->b7_);
  std::swap(b8_, other->b8_);
  std::swap(b9_, other->b9_);
  std::swap(b10_, other->b10_);
  std::swap(b11_, other->b11_);
  std::swap(b12_, other->b12_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageRequestSetPlayerBullets::GetTypeName() const {
  return "MessageRequestSetPlayerBullets";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageRequestSetPlayerBullets

// required int64 roomId = 1 [default = 0];
bool MessageRequestSetPlayerBullets::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageRequestSetPlayerBullets::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageRequestSetPlayerBullets::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
 ::google::protobuf::int64 MessageRequestSetPlayerBullets::roomid() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.roomId)
  return roomid_;
}
 void MessageRequestSetPlayerBullets::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.roomId)
}

// required bool b1 = 2 [default = false];
bool MessageRequestSetPlayerBullets::has_b1() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b1() {
  _has_bits_[0] |= 0x00000002u;
}
void MessageRequestSetPlayerBullets::clear_has_b1() {
  _has_bits_[0] &= ~0x00000002u;
}
void MessageRequestSetPlayerBullets::clear_b1() {
  b1_ = false;
  clear_has_b1();
}
 bool MessageRequestSetPlayerBullets::b1() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b1)
  return b1_;
}
 void MessageRequestSetPlayerBullets::set_b1(bool value) {
  set_has_b1();
  b1_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b1)
}

// required bool b2 = 3 [default = false];
bool MessageRequestSetPlayerBullets::has_b2() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b2() {
  _has_bits_[0] |= 0x00000004u;
}
void MessageRequestSetPlayerBullets::clear_has_b2() {
  _has_bits_[0] &= ~0x00000004u;
}
void MessageRequestSetPlayerBullets::clear_b2() {
  b2_ = false;
  clear_has_b2();
}
 bool MessageRequestSetPlayerBullets::b2() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b2)
  return b2_;
}
 void MessageRequestSetPlayerBullets::set_b2(bool value) {
  set_has_b2();
  b2_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b2)
}

// required bool b3 = 4 [default = false];
bool MessageRequestSetPlayerBullets::has_b3() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b3() {
  _has_bits_[0] |= 0x00000008u;
}
void MessageRequestSetPlayerBullets::clear_has_b3() {
  _has_bits_[0] &= ~0x00000008u;
}
void MessageRequestSetPlayerBullets::clear_b3() {
  b3_ = false;
  clear_has_b3();
}
 bool MessageRequestSetPlayerBullets::b3() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b3)
  return b3_;
}
 void MessageRequestSetPlayerBullets::set_b3(bool value) {
  set_has_b3();
  b3_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b3)
}

// required bool b4 = 5 [default = false];
bool MessageRequestSetPlayerBullets::has_b4() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b4() {
  _has_bits_[0] |= 0x00000010u;
}
void MessageRequestSetPlayerBullets::clear_has_b4() {
  _has_bits_[0] &= ~0x00000010u;
}
void MessageRequestSetPlayerBullets::clear_b4() {
  b4_ = false;
  clear_has_b4();
}
 bool MessageRequestSetPlayerBullets::b4() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b4)
  return b4_;
}
 void MessageRequestSetPlayerBullets::set_b4(bool value) {
  set_has_b4();
  b4_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b4)
}

// required bool b5 = 6 [default = false];
bool MessageRequestSetPlayerBullets::has_b5() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b5() {
  _has_bits_[0] |= 0x00000020u;
}
void MessageRequestSetPlayerBullets::clear_has_b5() {
  _has_bits_[0] &= ~0x00000020u;
}
void MessageRequestSetPlayerBullets::clear_b5() {
  b5_ = false;
  clear_has_b5();
}
 bool MessageRequestSetPlayerBullets::b5() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b5)
  return b5_;
}
 void MessageRequestSetPlayerBullets::set_b5(bool value) {
  set_has_b5();
  b5_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b5)
}

// required bool b6 = 7 [default = false];
bool MessageRequestSetPlayerBullets::has_b6() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b6() {
  _has_bits_[0] |= 0x00000040u;
}
void MessageRequestSetPlayerBullets::clear_has_b6() {
  _has_bits_[0] &= ~0x00000040u;
}
void MessageRequestSetPlayerBullets::clear_b6() {
  b6_ = false;
  clear_has_b6();
}
 bool MessageRequestSetPlayerBullets::b6() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b6)
  return b6_;
}
 void MessageRequestSetPlayerBullets::set_b6(bool value) {
  set_has_b6();
  b6_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b6)
}

// required bool b7 = 8 [default = false];
bool MessageRequestSetPlayerBullets::has_b7() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b7() {
  _has_bits_[0] |= 0x00000080u;
}
void MessageRequestSetPlayerBullets::clear_has_b7() {
  _has_bits_[0] &= ~0x00000080u;
}
void MessageRequestSetPlayerBullets::clear_b7() {
  b7_ = false;
  clear_has_b7();
}
 bool MessageRequestSetPlayerBullets::b7() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b7)
  return b7_;
}
 void MessageRequestSetPlayerBullets::set_b7(bool value) {
  set_has_b7();
  b7_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b7)
}

// required bool b8 = 9 [default = false];
bool MessageRequestSetPlayerBullets::has_b8() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b8() {
  _has_bits_[0] |= 0x00000100u;
}
void MessageRequestSetPlayerBullets::clear_has_b8() {
  _has_bits_[0] &= ~0x00000100u;
}
void MessageRequestSetPlayerBullets::clear_b8() {
  b8_ = false;
  clear_has_b8();
}
 bool MessageRequestSetPlayerBullets::b8() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b8)
  return b8_;
}
 void MessageRequestSetPlayerBullets::set_b8(bool value) {
  set_has_b8();
  b8_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b8)
}

// required bool b9 = 10 [default = false];
bool MessageRequestSetPlayerBullets::has_b9() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b9() {
  _has_bits_[0] |= 0x00000200u;
}
void MessageRequestSetPlayerBullets::clear_has_b9() {
  _has_bits_[0] &= ~0x00000200u;
}
void MessageRequestSetPlayerBullets::clear_b9() {
  b9_ = false;
  clear_has_b9();
}
 bool MessageRequestSetPlayerBullets::b9() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b9)
  return b9_;
}
 void MessageRequestSetPlayerBullets::set_b9(bool value) {
  set_has_b9();
  b9_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b9)
}

// required bool b10 = 11 [default = false];
bool MessageRequestSetPlayerBullets::has_b10() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b10() {
  _has_bits_[0] |= 0x00000400u;
}
void MessageRequestSetPlayerBullets::clear_has_b10() {
  _has_bits_[0] &= ~0x00000400u;
}
void MessageRequestSetPlayerBullets::clear_b10() {
  b10_ = false;
  clear_has_b10();
}
 bool MessageRequestSetPlayerBullets::b10() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b10)
  return b10_;
}
 void MessageRequestSetPlayerBullets::set_b10(bool value) {
  set_has_b10();
  b10_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b10)
}

// required bool b11 = 12 [default = false];
bool MessageRequestSetPlayerBullets::has_b11() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b11() {
  _has_bits_[0] |= 0x00000800u;
}
void MessageRequestSetPlayerBullets::clear_has_b11() {
  _has_bits_[0] &= ~0x00000800u;
}
void MessageRequestSetPlayerBullets::clear_b11() {
  b11_ = false;
  clear_has_b11();
}
 bool MessageRequestSetPlayerBullets::b11() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b11)
  return b11_;
}
 void MessageRequestSetPlayerBullets::set_b11(bool value) {
  set_has_b11();
  b11_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b11)
}

// required bool b12 = 13 [default = false];
bool MessageRequestSetPlayerBullets::has_b12() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
void MessageRequestSetPlayerBullets::set_has_b12() {
  _has_bits_[0] |= 0x00001000u;
}
void MessageRequestSetPlayerBullets::clear_has_b12() {
  _has_bits_[0] &= ~0x00001000u;
}
void MessageRequestSetPlayerBullets::clear_b12() {
  b12_ = false;
  clear_has_b12();
}
 bool MessageRequestSetPlayerBullets::b12() const {
  // @@protoc_insertion_point(field_get:MessageRequestSetPlayerBullets.b12)
  return b12_;
}
 void MessageRequestSetPlayerBullets::set_b12(bool value) {
  set_has_b12();
  b12_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestSetPlayerBullets.b12)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
