// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRequestCheckApi.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageRequestCheckApi.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageRequestCheckApi_2eproto() {
  delete MessageRequestCheckApi::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageRequestCheckApi_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageRequestCheckApi_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  MessageRequestCheckApi::default_instance_ = new MessageRequestCheckApi();
  MessageRequestCheckApi::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageRequestCheckApi_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageRequestCheckApi_2eproto_once_);
void protobuf_AddDesc_MessageRequestCheckApi_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageRequestCheckApi_2eproto_once_,
                 &protobuf_AddDesc_MessageRequestCheckApi_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageRequestCheckApi_2eproto {
  StaticDescriptorInitializer_MessageRequestCheckApi_2eproto() {
    protobuf_AddDesc_MessageRequestCheckApi_2eproto();
  }
} static_descriptor_initializer_MessageRequestCheckApi_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageRequestCheckApi(
    MessageRequestCheckApi* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageRequestCheckApi::kVersionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageRequestCheckApi::MessageRequestCheckApi()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageRequestCheckApi)
}

void MessageRequestCheckApi::InitAsDefaultInstance() {
}

MessageRequestCheckApi::MessageRequestCheckApi(const MessageRequestCheckApi& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageRequestCheckApi)
}

void MessageRequestCheckApi::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageRequestCheckApi::~MessageRequestCheckApi() {
  // @@protoc_insertion_point(destructor:MessageRequestCheckApi)
  SharedDtor();
}

void MessageRequestCheckApi::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  version_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MessageRequestCheckApi::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageRequestCheckApi& MessageRequestCheckApi::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageRequestCheckApi_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageRequestCheckApi_2eproto();
#endif
  return *default_instance_;
}

MessageRequestCheckApi* MessageRequestCheckApi::default_instance_ = NULL;

MessageRequestCheckApi* MessageRequestCheckApi::New(::google::protobuf::Arena* arena) const {
  MessageRequestCheckApi* n = new MessageRequestCheckApi;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageRequestCheckApi::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageRequestCheckApi)
  if (has_version()) {
    version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageRequestCheckApi::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageRequestCheckApi, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageRequestCheckApi)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required string version = 1 [default = ""];
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_version()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageRequestCheckApi)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageRequestCheckApi)
  return false;
#undef DO_
}

void MessageRequestCheckApi::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageRequestCheckApi)
  // required string version = 1 [default = ""];
  if (has_version()) {
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->version(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageRequestCheckApi)
}

int MessageRequestCheckApi::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageRequestCheckApi)
  int total_size = 0;

  // required string version = 1 [default = ""];
  if (has_version()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->version());
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageRequestCheckApi::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageRequestCheckApi*>(&from));
}

void MessageRequestCheckApi::MergeFrom(const MessageRequestCheckApi& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageRequestCheckApi)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_version()) {
      set_has_version();
      version_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.version_);
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageRequestCheckApi::CopyFrom(const MessageRequestCheckApi& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageRequestCheckApi)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageRequestCheckApi::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MessageRequestCheckApi::Swap(MessageRequestCheckApi* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageRequestCheckApi::InternalSwap(MessageRequestCheckApi* other) {
  version_.Swap(&other->version_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageRequestCheckApi::GetTypeName() const {
  return "MessageRequestCheckApi";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageRequestCheckApi

// required string version = 1 [default = ""];
bool MessageRequestCheckApi::has_version() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageRequestCheckApi::set_has_version() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageRequestCheckApi::clear_has_version() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageRequestCheckApi::clear_version() {
  version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_version();
}
 const ::std::string& MessageRequestCheckApi::version() const {
  // @@protoc_insertion_point(field_get:MessageRequestCheckApi.version)
  return version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageRequestCheckApi::set_version(const ::std::string& value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MessageRequestCheckApi.version)
}
 void MessageRequestCheckApi::set_version(const char* value) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MessageRequestCheckApi.version)
}
 void MessageRequestCheckApi::set_version(const char* value, size_t size) {
  set_has_version();
  version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MessageRequestCheckApi.version)
}
 ::std::string* MessageRequestCheckApi::mutable_version() {
  set_has_version();
  // @@protoc_insertion_point(field_mutable:MessageRequestCheckApi.version)
  return version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* MessageRequestCheckApi::release_version() {
  // @@protoc_insertion_point(field_release:MessageRequestCheckApi.version)
  clear_has_version();
  return version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void MessageRequestCheckApi::set_allocated_version(::std::string* version) {
  if (version != NULL) {
    set_has_version();
  } else {
    clear_has_version();
  }
  version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), version);
  // @@protoc_insertion_point(field_set_allocated:MessageRequestCheckApi.version)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
