// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageRequestRoomPlayerList.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageRequestRoomPlayerList.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageRequestRoomPlayerList_2eproto() {
  delete MessageRequestRoomPlayerList::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  MessageRequestRoomPlayerList::default_instance_ = new MessageRequestRoomPlayerList();
  MessageRequestRoomPlayerList::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageRequestRoomPlayerList_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto_once_);
void protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto_once_,
                 &protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageRequestRoomPlayerList_2eproto {
  StaticDescriptorInitializer_MessageRequestRoomPlayerList_2eproto() {
    protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto();
  }
} static_descriptor_initializer_MessageRequestRoomPlayerList_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageRequestRoomPlayerList(
    MessageRequestRoomPlayerList* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageRequestRoomPlayerList::kRoomIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageRequestRoomPlayerList::MessageRequestRoomPlayerList()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageRequestRoomPlayerList)
}

void MessageRequestRoomPlayerList::InitAsDefaultInstance() {
}

MessageRequestRoomPlayerList::MessageRequestRoomPlayerList(const MessageRequestRoomPlayerList& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageRequestRoomPlayerList)
}

void MessageRequestRoomPlayerList::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  roomid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageRequestRoomPlayerList::~MessageRequestRoomPlayerList() {
  // @@protoc_insertion_point(destructor:MessageRequestRoomPlayerList)
  SharedDtor();
}

void MessageRequestRoomPlayerList::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
  }
}

void MessageRequestRoomPlayerList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageRequestRoomPlayerList& MessageRequestRoomPlayerList::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageRequestRoomPlayerList_2eproto();
#endif
  return *default_instance_;
}

MessageRequestRoomPlayerList* MessageRequestRoomPlayerList::default_instance_ = NULL;

MessageRequestRoomPlayerList* MessageRequestRoomPlayerList::New(::google::protobuf::Arena* arena) const {
  MessageRequestRoomPlayerList* n = new MessageRequestRoomPlayerList;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageRequestRoomPlayerList::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageRequestRoomPlayerList)
  roomid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageRequestRoomPlayerList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageRequestRoomPlayerList, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageRequestRoomPlayerList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 roomId = 1 [default = 0];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &roomid_)));
          set_has_roomid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageRequestRoomPlayerList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageRequestRoomPlayerList)
  return false;
#undef DO_
}

void MessageRequestRoomPlayerList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageRequestRoomPlayerList)
  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->roomid(), output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageRequestRoomPlayerList)
}

int MessageRequestRoomPlayerList::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageRequestRoomPlayerList)
  int total_size = 0;

  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageRequestRoomPlayerList::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageRequestRoomPlayerList*>(&from));
}

void MessageRequestRoomPlayerList::MergeFrom(const MessageRequestRoomPlayerList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageRequestRoomPlayerList)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_roomid()) {
      set_roomid(from.roomid());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageRequestRoomPlayerList::CopyFrom(const MessageRequestRoomPlayerList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageRequestRoomPlayerList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageRequestRoomPlayerList::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  return true;
}

void MessageRequestRoomPlayerList::Swap(MessageRequestRoomPlayerList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageRequestRoomPlayerList::InternalSwap(MessageRequestRoomPlayerList* other) {
  std::swap(roomid_, other->roomid_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageRequestRoomPlayerList::GetTypeName() const {
  return "MessageRequestRoomPlayerList";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageRequestRoomPlayerList

// required int64 roomId = 1 [default = 0];
bool MessageRequestRoomPlayerList::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageRequestRoomPlayerList::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageRequestRoomPlayerList::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageRequestRoomPlayerList::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
 ::google::protobuf::int64 MessageRequestRoomPlayerList::roomid() const {
  // @@protoc_insertion_point(field_get:MessageRequestRoomPlayerList.roomId)
  return roomid_;
}
 void MessageRequestRoomPlayerList::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageRequestRoomPlayerList.roomId)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
