// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseTimeToEnd.proto

#ifndef PROTOBUF_MessageResponseTimeToEnd_2eproto__INCLUDED
#define PROTOBUF_MessageResponseTimeToEnd_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "MessageResponseRoundPlayerBang.pb.h"
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_MessageResponseTimeToEnd_2eproto();
void protobuf_AssignDesc_MessageResponseTimeToEnd_2eproto();
void protobuf_ShutdownFile_MessageResponseTimeToEnd_2eproto();

class MessageResponseTimeToEnd;

// ===================================================================

class MessageResponseTimeToEnd : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:MessageResponseTimeToEnd) */ {
 public:
  MessageResponseTimeToEnd();
  virtual ~MessageResponseTimeToEnd();

  MessageResponseTimeToEnd(const MessageResponseTimeToEnd& from);

  inline MessageResponseTimeToEnd& operator=(const MessageResponseTimeToEnd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::std::string& unknown_fields() const {
    return _unknown_fields_.GetNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  inline ::std::string* mutable_unknown_fields() {
    return _unknown_fields_.MutableNoArena(
        &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }

  static const MessageResponseTimeToEnd& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const MessageResponseTimeToEnd* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(MessageResponseTimeToEnd* other);

  // implements Message ----------------------------------------------

  inline MessageResponseTimeToEnd* New() const { return New(NULL); }

  MessageResponseTimeToEnd* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const MessageResponseTimeToEnd& from);
  void MergeFrom(const MessageResponseTimeToEnd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MessageResponseTimeToEnd* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 roomId = 1 [default = 0];
  bool has_roomid() const;
  void clear_roomid();
  static const int kRoomIdFieldNumber = 1;
  ::google::protobuf::int64 roomid() const;
  void set_roomid(::google::protobuf::int64 value);

  // optional .MessageResponseRoundPlayerBang gameWinner = 2;
  bool has_gamewinner() const;
  void clear_gamewinner();
  static const int kGameWinnerFieldNumber = 2;
  const ::MessageResponseRoundPlayerBang& gamewinner() const;
  ::MessageResponseRoundPlayerBang* mutable_gamewinner();
  ::MessageResponseRoundPlayerBang* release_gamewinner();
  void set_allocated_gamewinner(::MessageResponseRoundPlayerBang* gamewinner);

  // @@protoc_insertion_point(class_scope:MessageResponseTimeToEnd)
 private:
  inline void set_has_roomid();
  inline void clear_has_roomid();
  inline void set_has_gamewinner();
  inline void clear_has_gamewinner();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::int64 roomid_;
  ::MessageResponseRoundPlayerBang* gamewinner_;
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_MessageResponseTimeToEnd_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_MessageResponseTimeToEnd_2eproto();
  #endif
  friend void protobuf_AssignDesc_MessageResponseTimeToEnd_2eproto();
  friend void protobuf_ShutdownFile_MessageResponseTimeToEnd_2eproto();

  void InitAsDefaultInstance();
  static MessageResponseTimeToEnd* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseTimeToEnd

// required int64 roomId = 1 [default = 0];
inline bool MessageResponseTimeToEnd::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageResponseTimeToEnd::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageResponseTimeToEnd::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageResponseTimeToEnd::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
inline ::google::protobuf::int64 MessageResponseTimeToEnd::roomid() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToEnd.roomId)
  return roomid_;
}
inline void MessageResponseTimeToEnd::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseTimeToEnd.roomId)
}

// optional .MessageResponseRoundPlayerBang gameWinner = 2;
inline bool MessageResponseTimeToEnd::has_gamewinner() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageResponseTimeToEnd::set_has_gamewinner() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageResponseTimeToEnd::clear_has_gamewinner() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageResponseTimeToEnd::clear_gamewinner() {
  if (gamewinner_ != NULL) gamewinner_->::MessageResponseRoundPlayerBang::Clear();
  clear_has_gamewinner();
}
inline const ::MessageResponseRoundPlayerBang& MessageResponseTimeToEnd::gamewinner() const {
  // @@protoc_insertion_point(field_get:MessageResponseTimeToEnd.gameWinner)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return gamewinner_ != NULL ? *gamewinner_ : *default_instance().gamewinner_;
#else
  return gamewinner_ != NULL ? *gamewinner_ : *default_instance_->gamewinner_;
#endif
}
inline ::MessageResponseRoundPlayerBang* MessageResponseTimeToEnd::mutable_gamewinner() {
  set_has_gamewinner();
  if (gamewinner_ == NULL) {
    gamewinner_ = new ::MessageResponseRoundPlayerBang;
  }
  // @@protoc_insertion_point(field_mutable:MessageResponseTimeToEnd.gameWinner)
  return gamewinner_;
}
inline ::MessageResponseRoundPlayerBang* MessageResponseTimeToEnd::release_gamewinner() {
  // @@protoc_insertion_point(field_release:MessageResponseTimeToEnd.gameWinner)
  clear_has_gamewinner();
  ::MessageResponseRoundPlayerBang* temp = gamewinner_;
  gamewinner_ = NULL;
  return temp;
}
inline void MessageResponseTimeToEnd::set_allocated_gamewinner(::MessageResponseRoundPlayerBang* gamewinner) {
  delete gamewinner_;
  gamewinner_ = gamewinner;
  if (gamewinner) {
    set_has_gamewinner();
  } else {
    clear_has_gamewinner();
  }
  // @@protoc_insertion_point(field_set_allocated:MessageResponseTimeToEnd.gameWinner)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageResponseTimeToEnd_2eproto__INCLUDED
