// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageResponseRoomPlayerBang.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageResponseRoomPlayerBang.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/io/zero_copy_stream_impl_lite.h>
// @@protoc_insertion_point(includes)

void protobuf_ShutdownFile_MessageResponseRoomPlayerBang_2eproto() {
  delete MessageResponseRoomPlayerBang::default_instance_;
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
void protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#else
void protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#endif
  ::protobuf_AddDesc_MessageResponseRoundPlayerBang_2eproto();
  MessageResponseRoomPlayerBang::default_instance_ = new MessageResponseRoomPlayerBang();
  MessageResponseRoomPlayerBang::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageResponseRoomPlayerBang_2eproto);
}

#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto_once_);
void protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto_once_,
                 &protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto_impl);
}
#else
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageResponseRoomPlayerBang_2eproto {
  StaticDescriptorInitializer_MessageResponseRoomPlayerBang_2eproto() {
    protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto();
  }
} static_descriptor_initializer_MessageResponseRoomPlayerBang_2eproto_;
#endif

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

static ::std::string* MutableUnknownFieldsForMessageResponseRoomPlayerBang(
    MessageResponseRoomPlayerBang* ptr) {
  return ptr->mutable_unknown_fields();
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MessageResponseRoomPlayerBang::kRoomIdFieldNumber;
const int MessageResponseRoomPlayerBang::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MessageResponseRoomPlayerBang::MessageResponseRoomPlayerBang()
  : ::google::protobuf::MessageLite(), _arena_ptr_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageResponseRoomPlayerBang)
}

void MessageResponseRoomPlayerBang::InitAsDefaultInstance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  result_ = const_cast< ::MessageResponseRoundPlayerBang*>(
      ::MessageResponseRoundPlayerBang::internal_default_instance());
#else
  result_ = const_cast< ::MessageResponseRoundPlayerBang*>(&::MessageResponseRoundPlayerBang::default_instance());
#endif
}

MessageResponseRoomPlayerBang::MessageResponseRoomPlayerBang(const MessageResponseRoomPlayerBang& from)
  : ::google::protobuf::MessageLite(),
    _arena_ptr_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageResponseRoomPlayerBang)
}

void MessageResponseRoomPlayerBang::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  _unknown_fields_.UnsafeSetDefault(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  roomid_ = GOOGLE_LONGLONG(0);
  result_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageResponseRoomPlayerBang::~MessageResponseRoomPlayerBang() {
  // @@protoc_insertion_point(destructor:MessageResponseRoomPlayerBang)
  SharedDtor();
}

void MessageResponseRoomPlayerBang::SharedDtor() {
  _unknown_fields_.DestroyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  if (this != &default_instance()) {
  #else
  if (this != default_instance_) {
  #endif
    delete result_;
  }
}

void MessageResponseRoomPlayerBang::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const MessageResponseRoomPlayerBang& MessageResponseRoomPlayerBang::default_instance() {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto();
#else
  if (default_instance_ == NULL) protobuf_AddDesc_MessageResponseRoomPlayerBang_2eproto();
#endif
  return *default_instance_;
}

MessageResponseRoomPlayerBang* MessageResponseRoomPlayerBang::default_instance_ = NULL;

MessageResponseRoomPlayerBang* MessageResponseRoomPlayerBang::New(::google::protobuf::Arena* arena) const {
  MessageResponseRoomPlayerBang* n = new MessageResponseRoomPlayerBang;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MessageResponseRoomPlayerBang::Clear() {
// @@protoc_insertion_point(message_clear_start:MessageResponseRoomPlayerBang)
  if (_has_bits_[0 / 32] & 3u) {
    roomid_ = GOOGLE_LONGLONG(0);
    if (has_result()) {
      if (result_ != NULL) result_->::MessageResponseRoundPlayerBang::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  _unknown_fields_.ClearToEmptyNoArena(
      &::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MessageResponseRoomPlayerBang::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  ::google::protobuf::io::LazyStringOutputStream unknown_fields_string(
      ::google::protobuf::internal::NewPermanentCallback(
          &MutableUnknownFieldsForMessageResponseRoomPlayerBang, this));
  ::google::protobuf::io::CodedOutputStream unknown_fields_stream(
      &unknown_fields_string, false);
  // @@protoc_insertion_point(parse_start:MessageResponseRoomPlayerBang)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int64 roomId = 1 [default = 0];
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &roomid_)));
          set_has_roomid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_result;
        break;
      }

      // required .MessageResponseRoundPlayerBang result = 2;
      case 2: {
        if (tag == 18) {
         parse_result:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_result()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(
            input, tag, &unknown_fields_stream));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageResponseRoomPlayerBang)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageResponseRoomPlayerBang)
  return false;
#undef DO_
}

void MessageResponseRoomPlayerBang::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageResponseRoomPlayerBang)
  // required int64 roomId = 1 [default = 0];
  if (has_roomid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(1, this->roomid(), output);
  }

  // required .MessageResponseRoundPlayerBang result = 2;
  if (has_result()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessage(
      2, *this->result_, output);
  }

  output->WriteRaw(unknown_fields().data(),
                   static_cast<int>(unknown_fields().size()));
  // @@protoc_insertion_point(serialize_end:MessageResponseRoomPlayerBang)
}

int MessageResponseRoomPlayerBang::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:MessageResponseRoomPlayerBang)
  int total_size = 0;

  if (has_roomid()) {
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());
  }

  if (has_result()) {
    // required .MessageResponseRoundPlayerBang result = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->result_);
  }

  return total_size;
}
int MessageResponseRoomPlayerBang::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:MessageResponseRoomPlayerBang)
  int total_size = 0;

  if (((_has_bits_[0] & 0x00000003) ^ 0x00000003) == 0) {  // All required fields are present.
    // required int64 roomId = 1 [default = 0];
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->roomid());

    // required .MessageResponseRoundPlayerBang result = 2;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->result_);

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  total_size += unknown_fields().size();

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageResponseRoomPlayerBang::CheckTypeAndMergeFrom(
    const ::google::protobuf::MessageLite& from) {
  MergeFrom(*::google::protobuf::down_cast<const MessageResponseRoomPlayerBang*>(&from));
}

void MessageResponseRoomPlayerBang::MergeFrom(const MessageResponseRoomPlayerBang& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MessageResponseRoomPlayerBang)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_roomid()) {
      set_roomid(from.roomid());
    }
    if (from.has_result()) {
      mutable_result()->::MessageResponseRoundPlayerBang::MergeFrom(from.result());
    }
  }
  if (!from.unknown_fields().empty()) {
    mutable_unknown_fields()->append(from.unknown_fields());
  }
}

void MessageResponseRoomPlayerBang::CopyFrom(const MessageResponseRoomPlayerBang& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MessageResponseRoomPlayerBang)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageResponseRoomPlayerBang::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  if (has_result()) {
    if (!this->result_->IsInitialized()) return false;
  }
  return true;
}

void MessageResponseRoomPlayerBang::Swap(MessageResponseRoomPlayerBang* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MessageResponseRoomPlayerBang::InternalSwap(MessageResponseRoomPlayerBang* other) {
  std::swap(roomid_, other->roomid_);
  std::swap(result_, other->result_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _unknown_fields_.Swap(&other->_unknown_fields_);
  std::swap(_cached_size_, other->_cached_size_);
}

::std::string MessageResponseRoomPlayerBang::GetTypeName() const {
  return "MessageResponseRoomPlayerBang";
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MessageResponseRoomPlayerBang

// required int64 roomId = 1 [default = 0];
bool MessageResponseRoomPlayerBang::has_roomid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void MessageResponseRoomPlayerBang::set_has_roomid() {
  _has_bits_[0] |= 0x00000001u;
}
void MessageResponseRoomPlayerBang::clear_has_roomid() {
  _has_bits_[0] &= ~0x00000001u;
}
void MessageResponseRoomPlayerBang::clear_roomid() {
  roomid_ = GOOGLE_LONGLONG(0);
  clear_has_roomid();
}
 ::google::protobuf::int64 MessageResponseRoomPlayerBang::roomid() const {
  // @@protoc_insertion_point(field_get:MessageResponseRoomPlayerBang.roomId)
  return roomid_;
}
 void MessageResponseRoomPlayerBang::set_roomid(::google::protobuf::int64 value) {
  set_has_roomid();
  roomid_ = value;
  // @@protoc_insertion_point(field_set:MessageResponseRoomPlayerBang.roomId)
}

// required .MessageResponseRoundPlayerBang result = 2;
bool MessageResponseRoomPlayerBang::has_result() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void MessageResponseRoomPlayerBang::set_has_result() {
  _has_bits_[0] |= 0x00000002u;
}
void MessageResponseRoomPlayerBang::clear_has_result() {
  _has_bits_[0] &= ~0x00000002u;
}
void MessageResponseRoomPlayerBang::clear_result() {
  if (result_ != NULL) result_->::MessageResponseRoundPlayerBang::Clear();
  clear_has_result();
}
const ::MessageResponseRoundPlayerBang& MessageResponseRoomPlayerBang::result() const {
  // @@protoc_insertion_point(field_get:MessageResponseRoomPlayerBang.result)
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  return result_ != NULL ? *result_ : *default_instance().result_;
#else
  return result_ != NULL ? *result_ : *default_instance_->result_;
#endif
}
::MessageResponseRoundPlayerBang* MessageResponseRoomPlayerBang::mutable_result() {
  set_has_result();
  if (result_ == NULL) {
    result_ = new ::MessageResponseRoundPlayerBang;
  }
  // @@protoc_insertion_point(field_mutable:MessageResponseRoomPlayerBang.result)
  return result_;
}
::MessageResponseRoundPlayerBang* MessageResponseRoomPlayerBang::release_result() {
  // @@protoc_insertion_point(field_release:MessageResponseRoomPlayerBang.result)
  clear_has_result();
  ::MessageResponseRoundPlayerBang* temp = result_;
  result_ = NULL;
  return temp;
}
void MessageResponseRoomPlayerBang::set_allocated_result(::MessageResponseRoundPlayerBang* result) {
  delete result_;
  result_ = result;
  if (result) {
    set_has_result();
  } else {
    clear_has_result();
  }
  // @@protoc_insertion_point(field_set_allocated:MessageResponseRoomPlayerBang.result)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
